Repository nim-lang/Nim, pull requests merged in 2018-12, with the labels that each got.

#9874 fix #9872: setLen now works properly at CT
  compiler/vm.nim
  tests/vm/tsetlen.nim
Labels: merge_when_passes_CI

#9916 refs #9906; --errorMax:10 allows stopping after 10 errors (more robust than nim check)
  compiler/commands.nim
  doc/advopt.txt
Labels: Error messages

#9755 Fix for #9243, nre returns "" instead of nil for missing matches
  changelog.md
  lib/impure/nre.nim
  lib/impure/nre/private/util.nim
  tests/stdlib/nre/captures.nim
  tests/stdlib/nre/match.nim
  tests/stdlib/nre/replace.nim
Labels: Stdlib

#9968 Allow an escape hatch for platform specific flags/default override
  lib/pure/memfiles.nim
Labels: merge_when_passes_CI

#10012 Add project directory to include path
  compiler/extccomp.nim
Labels: merge_when_passes_CI

#9925 add `getCurrentCompilerExe` to vmops (eg allows to get nim compiler at CT); add tests for vmops
  changelog.md
  compiler/vmops.nim
  lib/pure/os.nim
  lib/system/nimscript.nim
  tests/vm/tgorge.nim
  tests/vm/tvmops.nim
Labels: VM

#10022 document NIM_EXTERNC for `emit` that avoids link errors with `nim cpp`
  doc/manual.rst
Labels: C++ codegen, Documentation

#9981 proc does not take untyped/typed as argument
  compiler/semtypes.nim
  tests/proc/typed.nim
  tests/proc/untyped.nim
Labels: merge_when_passes_CI

#10048 Add call to hostnamectl in detectOsImpl
  lib/pure/distros.nim
Labels: merge_when_passes_CI

#10044 lots of testament bug fixes and improvements:
  testament/categories.nim
  testament/tester.nim
  tests/testament/tshouldfail.nim
Labels: Test suite

#10069 clarify doc for <= on tuple uses lexicographic order
  lib/system.nim
Labels: Documentation

#10115 document --profiler:on
  doc/advopt.txt
Labels: Documentation, Profiling/Debugging

#10124 refs #10121
  lib/pure/times.nim
Labels: Profiling/Debugging
