Repository nim-lang/Nim, pull requests merged in 2018-10, with the labels that each got.

#9171 Use runnableExamples for nre example code where possible
  lib/impure/nre.nim
Labels: Documentation

#9234 [cleanup] remove `xmldom` and `xmldomparser`
  doc/lib.rst
  lib/pure/xmldom.nim
  lib/pure/xmldomparser.nim
  lib/pure/xmltree.nim
  tools/kochdocs.nim
  web/website.ini
Labels: Hacktoberfest

#9546 more examples for `mod` and `div`, plus corrections (closes #4676)
  lib/pure/math.nim
  lib/system.nim
Labels: Documentation

#9539 Eliminate floating point arithmatic in nre
  lib/impure/nre.nim
Labels: Performance, Stdlib

#9542 Change documentation details (closes #5525)
  compiler/docgen.nim
  nimdoc/testproject/expected/subdir/subdir_b/utils.html
  nimdoc/testproject/expected/testproject.html
Labels: Documentation
