Repository nim-lang/Nim, pull requests merged in 2019-01, with the labels that each got.

#10151 Deprecate gc v2
  compiler/commands.nim
  compiler/importer.nim
  compiler/lineinfos.nim
  compiler/lookups.nim
  compiler/modulepaths.nim
  compiler/parser.nim
  compiler/pragmas.nim
  compiler/semexprs.nim
  compiler/semstmts.nim
  compiler/semtypes.nim
  compiler/suggest.nim
  doc/advopt.txt
Labels: merge_when_passes_CI

#10196 move up `runnableExamples` definition so can be used more in system.nim ; document rounding scheme used
  lib/system.nim
Labels: Documentation, runnableExamples

#10089 testament megatest: we can now tell which test failed; helps debugging and prevents certain bugs, plus other fixes
  .gitignore
  testament/categories.nim
  testament/tester.nim
Labels: Test suite

#10183 [CI] fix #10041 move bulk of `travis` and `appveyor` logic to koch.nim
  .travis.yml
  appveyor.yml
  koch.nim
  tools/kochdocs.nim
Labels: CI

#10274 fix #10273 execShellCmd now returns nonzero when child killed with signal + other fixes
  .gitignore
  lib/pure/os.nim
  lib/pure/osproc.nim
  testament/lib/stdtest/specialpaths.nim
  tests/nim.cfg
  tests/stdlib/t10231.nim
  tests/stdlib/tos.nim
  tests/stdlib/tosproc.nim
Labels: osproc

#10294 fix (last?) remaining leftover from #9647 : use nimf as standardized extension for source code filters
  testament/htmlgen.nim
  testament/testamenthtml.nimf
Labels: Easy

#10303 refs #10249 #10266; each command logged only if --verboseCommands:true
  testament/tester.nim
Labels: Test suite

#10313 fix twrong_refcounts in nim cpp mode
  tests/parallel/twrong_refcounts.nim
Labels: C++ codegen, CI, import

#10312 [CI] runCI runs `kochExec "boot"` regardless of nim mode
  koch.nim
Labels: CI

#10310 fix #10305 nim cpp is now nan-correct at CT
  compiler/extccomp.nim
  doc/nimc.rst
  tests/float/tfloatnan.nim
Labels: C++ codegen, CI

#10306 improve vmgen.codeListing formatting
  compiler/dfa.nim
  compiler/vm.nim
  compiler/vmgen.nim
Labels: VM

#10304 parseopt2.cmdLineRest is now correct too
  lib/pure/parseopt2.nim
  tests/misc/tparseopt.nim
Labels: command line

#10324 properly fix #10030 by skipping all external configs
  build_all.sh
  doc/advopt.txt
  koch.nim
Labels: Nimscript, bootstrapping

#10315 [CI] now enables `NIM_COMPILE_TO_CPP=true` to run without allow_failures
  .travis.yml
  koch.nim
  lib/system.nim
  tests/exception/t9657.nim
Labels: C++ codegen, CI

#10332 Remove long deprecated stuff
  lib/impure/re.nim
  lib/js/dom.nim
  lib/pure/cgi.nim
  lib/pure/collections/critbits.nim
  lib/pure/collections/intsets.nim
  lib/pure/collections/sets.nim
  lib/pure/httpclient.nim
  lib/pure/nativesockets.nim
  lib/pure/net.nim
  lib/pure/osproc.nim
  lib/pure/parseopt2.nim
  lib/pure/parseutils.nim
  lib/pure/uri.nim
  tests/async/twinasyncrw.nim
  tests/manyloc/nake/nakefile.nim
Labels: merge_when_passes_CI

#10349 parseutils: Updated documentation
  lib/pure/parseutils.nim
Labels: Documentation, merge_when_passes_CI

#10379 Fix spelling errors
  compiler/semexprs.nim
  lib/pure/includes/osseps.nim
  lib/pure/net.nim
  tests/stdlib/ttimes.nim
Labels: merge_when_passes_CI

#10402 Fix subtype conversion w/ varargs arguments
  compiler/sigmatch.nim
  tests/typerel/t4799.nim
  tests/typerel/t4799_1.nim
  tests/typerel/t4799_2.nim
  tests/typerel/t4799_3.nim
Labels: merge_when_passes_CI

#10398 parseopt: Updated documentation
  lib/pure/parseopt.nim
Labels: merge_when_passes_CI

#10415 Restore compatibility with old vcc versions
  compiler/cgen.nim
Labels: merge_when_passes_CI

#10419 Fix wrong integer types in odbcsql and db_odbc
  lib/impure/db_odbc.nim
  lib/wrappers/odbcsql.nim
Labels: merge_when_passes_CI

#10354 Fix for issue #10342. better message for generic subclass instantiation
  compiler/semtypinst.nim
  compiler/types.nim
  tests/generics/tsubclassgenericerror.nim
  tests/generics/twrong_generic_object.nim
Labels: merge_when_passes_CI

#10422 Fix semantic analysis with noReturn proc in tail pos
  compiler/semstmts.nim
  tests/exception/texceptions.nim
Labels: merge_when_passes_CI

#10445 fix #9556 [backport]
  compiler/msgs.nim
Labels: merge_when_passes_CI

#10455 Fix exception tracking in try blocks
  compiler/sempass2.nim
  tests/effects/teffects7.nim
Labels: merge_when_passes_CI

#10435 add git diff hints to help with reviews
  doc/contributing.rst
Labels: Documentation

#10480 fix documentation css
  config/nimdoc.cfg
  nimdoc/testproject/expected/subdir/subdir_b/utils.html
  nimdoc/testproject/expected/testproject.html
  nimdoc/testproject/expected/theindex.html
Labels: merge_when_passes_CI

#10503 fix #9725
  doc/manual.rst
Labels: merge_when_passes_CI

#10505 Show correct address for ipv6 sockets
  lib/pure/net.nim
  lib/windows/winlean.nim
Labels: merge_when_passes_CI
