Repository nim-lang/Nim, pull requests merged in 2019-02, with the labels that each got.

#10522 Deprecate the times.countX procs
  lib/pure/times.nim
Labels: merge_when_passes_CI

#10525 brew (almost?) never requires sudo
  lib/pure/distros.nim
Labels: merge_when_passes_CI

#10573 prevent common user config to interfere with testament
  tests/config.nims
  tests/nim.cfg
Labels: Test suite

#10571 [doc] lots of fixes in doc/{contributing,docstyle}.rst
  doc/contributing.rst
  doc/docstyle.rst
Labels: Documentation

#10577 Fixes #10568: Fix null pointer dereference in address computation for incrSeqV3.
  compiler/ccgexprs.nim
Labels: merge_when_passes_CI

#10592 fix #10591 regression
  tests/macros/t8997.nim
Labels: Easy, Regression

#10590 followup on #10573: prevent common user config to interfere with testament (excessiveStackTrace)
  tests/config.nims
Labels: Easy, Test suite

#10582 Fix handling of reraise in effect tracking
  compiler/sempass2.nim
  tests/effects/teffects8.nim
Labels: merge_when_passes_CI

#10595 Fix codegen when debugger is enabled
  compiler/ccgstmts.nim
Labels: merge_when_passes_CI

#10496 compiler/[msgs, suggest]: improve highlighter accuracy
  compiler/msgs.nim
  compiler/suggest.nim
  nimsuggest/tests/tsetter_highlight.nim
  nimsuggest/tests/tsi_highlight.nim
Labels: merge_when_passes_CI

#10603 Add non-interactive installer flag (-y) to finish.nim
  tools/finish.nim
Labels: merge_when_passes_CI

#10549 new AppVeyor configuration that should test the compiler against sele…
  appveyor.yml
  koch.nim
  testament/important_packages.nim
Labels: merge_when_passes_CI

#10643 travis:upgrade to xenial (trusty end of life is april 2019)
  .travis.yml
Labels: CI, Easy

#10680 allow string insert in nimscript, fixes #10561
  lib/system.nim
Labels: merge_when_passes_CI

#10699 Small CI improvements
  .travis.yml
  appveyor.yml
Labels: merge_when_passes_CI

#10685 Prevent crash on pragma templates w/ generics
  compiler/pragmas.nim
  lib/core/macros.nim
  tests/pragmas/tcustom_pragma.nim
Labels: merge_when_passes_CI

#10660 fix #10659 `koch boot` fails on windows with choosenim-installed nim: proxyexe.nim error
  koch.nim
Labels: Easy

#10150 FFI at CT
  compiler/commands.nim
  compiler/evalffi.nim
  compiler/main.nim
  compiler/options.nim
  compiler/vm.nim
  compiler/vmdef.nim
  compiler/vmgen.nim
  koch.nim
  tests/vm/tevalffi.nim
Labels: Feature

#10152 Tuple unpacking now works for `for` vars
  changelog.md
  compiler/ccgexprs.nim
  compiler/lowerings.nim
  compiler/parser.nim
  compiler/semstmts.nim
  compiler/transf.nim
  tests/tuples/tfortupleunpack.nim
Labels: High Priority
