Repository nim-lang/Nim, pull requests merged in 2019-05, with the labels that each got.

#11172 Fix #11058
  compiler/semtypes.nim
  tests/metatype/tbindtypedesc.nim
Labels: merge_when_passes_CI

#11190 Update outdated ETimeout exception name
  lib/pure/net.nim
Labels: Documentation

#11199 Reallow float ranges in random module
  lib/pure/random.nim
Labels: merge_when_passes_CI

#7164 Make range checks in semConv
  changelog.md
  compiler/ast.nim
  compiler/semexprs.nim
  compiler/semfold.nim
  compiler/types.nim
  lib/posix/posix_nintendoswitch_consts.nim
  lib/pure/segfaults.nim
  lib/windows/winlean.nim
  tests/misc/tconv.nim
Labels: Next release

#11219 Testament print failed command
  testament/categories.nim
  testament/tester.nim
Labels: merge_when_passes_CI

#11260 fix #10952, UNC paths
  lib/pure/pathnorm.nim
  tests/stdlib/tos_unc.nim
Labels: merge_when_passes_CI

#11283 More specific error message for unsupported recursion in iterators
  compiler/semexprs.nim
  compiler/semstmts.nim
  tests/iter/treciter.nim
Labels: merge_when_passes_CI

#11288 fix #8395, fix #8734: normalize os.tailDir and os.parentDir
  lib/pure/os.nim
Labels: merge_when_passes_CI

#11291 fix #10910, optimize squaring and cubing
  lib/pure/math.nim
Labels: merge_when_passes_CI
