Repository nim-lang/Nim, pull requests merged in 2020-04, with the labels that each got.

#13832 fix "too many open files" 'leak' when running `--debugger:native`
  compiler/cgen.nim
  compiler/ndi.nim
Labels: merge_when_passes_CI

#13838 Deprecate PHP
  lib/system/gc_regions.nim
Labels: merge_when_passes_CI

#13844 renamed new std/pragmas.nim to std/byaddr.nim
  changelog.md
  lib/std/byaddr.nim
  tests/stdlib/tbyaddr.nim
Labels: Next release

#13837 feature/count
  changelog.md
  lib/pure/collections/sequtils.nim
Labels: Next release

#7508 Sourcemap for JS
  compiler/commands.nim
  compiler/jsgen.nim
  compiler/options.nim
  compiler/sourcemap.nim
Labels: S: Waiting on author

#13925 fix compiler crash in isUnresolvedSym [backport]
  compiler/semexprs.nim
Labels: merge_when_passes_CI

#13962 error msg for #13864
  compiler/semexprs.nim
  tests/arc/tref_cast_error.nim
Labels: merge_when_passes_CI

#14029 Fixes #14014
  compiler/spawn.nim
  tests/parallel/tsysspawn.nim
Labels: merge_when_passes_CI

#14135 Fix issue with stringifying incomplete types
  compiler/types.nim
Labels: merge_when_passes_CI

#14161 Fix #14160
  compiler/ccgexprs.nim
  tests/ccgbugs/t14160.nim
Labels: merge_when_passes_CI
