Repository nim-lang/Nim, pull requests merged in 2021-12, with the labels that each got.

#19191 Treat `do` with pragmas but no parameters as proc
  compiler/parser.nim
  doc/manual.rst
  tests/parser/tdo.nim
Labels: merge_when_passes_CI

#19212 Atomic inc/dec should use ATOMIC_SEQ_CST
  lib/system/atomics.nim
Labels: help wanted

#19228 remove `std/sharedstrings`
  changelog.md
  lib/deprecated/pure/sharedstrings.nim
  testament/testament.nim
Labels: merge_when_passes_CI

#19134 fixes a possible 'javascript:' protocol exploit [backport:1.0]
  lib/packages/docutils/rstgen.nim
  tests/stdlib/trstgen.nim
Labels: Showstopper, merge_when_passes_CI

#19299 Fix #19297 - fixing broken list after adding empty list
  lib/pure/collections/lists.nim
  tests/stdlib/tlists.nim
Labels: merge_when_passes_CI
