Repository nim-lang/Nim, pull requests merged in 2021-03, with the labels that each got.

#17203 use `-r:off` for runnableExamples that should compile but not run
  lib/impure/rdstdin.nim
  lib/pure/asynchttpserver.nim
  lib/pure/oids.nim
  lib/pure/sugar.nim
  lib/wrappers/linenoise/linenoise.nim
Labels: TODO: followup needed

#15951 add overload `add(a: var string, b: openArray[char])`
  changelog.md
  lib/std/strbasics.nim
  lib/system.nim
  tests/stdlib/tstrbasics.nim
  tests/vm/tstring_openarray.nim
Labels: merge_when_passes_CI

#17213 fixes #17173
  changelog.md
  lib/std/strbasics.nim
  lib/system.nim
  lib/system/strs_v2.nim
  tests/arc/t17173.nim
Labels: TODO: followup needed

#17232 attempt to fix #16374
  compiler/cgen.nim
  tests/ccgbugs/t16374.nim
Labels: merge_when_passes_CI

#17224 document copy on write behavior of string literals in arc/orc
  doc/destructors.rst
Labels: TODO: followup needed

#17242 followup #17225: simplify code after removing gc2, generational
  compiler/commands.nim
  compiler/nim.nim
  compiler/nimfix/nimfix.nim
  drnim/drnim.nim
  lib/system.nim
  lib/system/gc2.nim
  lib/system/mmdisp.nim
  lib/system/sysstr.nim
Labels: TODO: followup needed

#17189 followup #16871 asyncjs.then: allow pipelining procs returning futures
  lib/js/asyncjs.nim
  tests/js/tasyncjs.nim
  tests/js/tasyncjs_bad.nim
  tests/js/tasyncjs_pragma.nim
Labels: TODO: followup needed

#17165 reuse jsffi in json module
  lib/pure/json.nim
  tests/stdlib/t15835.nim
  tests/stdlib/talgorithm.nim
  tests/stdlib/tjson_unmarshall.nim
Labels: TODO: followup needed

#17248 Added assertion to clamp
  lib/pure/math.nim
  lib/system/comparisons.nim
Labels: merge_when_passes_CI

#12531 Add module jsfetch
  changelog.md
  lib/std/jsfetch.nim
  lib/std/jsformdata.nim
  lib/std/jsheaders.nim
  tools/kochdocs.nim
Labels: TODO: followup needed, merge_when_passes_CI

#17012 stdlib/os: add isAdmin
  changelog.md
  lib/pure/os.nim
  lib/windows/winlean.nim
  tests/stdlib/tos.nim
Labels: S: Waiting on author

#17272 add setutils.[]=
  changelog.md
  lib/std/setutils.nim
  tests/stdlib/tsetutils.nim
Labels: vote

#17297 improve test coverage for isolation
  tests/stdlib/isolation.nim
  tests/stdlib/tisolation.nim
Labels: merge_when_passes_CI

#17265 IC: compilerprocs are handled correctly
  compiler/ccgexprs.nim
  compiler/ic/cbackend.nim
  compiler/ic/dce.nim
  compiler/ic/packed_ast.nim
  compiler/ic/replayer.nim
  compiler/ic/to_packed_ast.nim
  compiler/modulegraphs.nim
  compiler/semdata.nim
Labels: merge_when_passes_CI

#17282 fix #13491 #17279 runnableExamples now don't get lost in translation
  compiler/docgen.nim
  compiler/renderer.nim
  lib/pure/sugar.nim
  tests/nimdoc/trunnableexamples.nim
Labels: TODO: followup needed

#17306 Add Portals
  changelog.md
  lib/pure/htmlgen.nim
Labels: merge_when_passes_CI

#17317 close #16607 add testcase
  tests/destructor/t16607.nim
Labels: merge_when_passes_CI

#17316 close #9440 add testcase
  tests/destructor/t9440.nim
Labels: merge_when_passes_CI

#17312 Improve the lists module
  lib/pure/collections/lists.nim
Labels: TODO: followup needed

#17281 add typetraits.OrdinalEnum, enumutils.symbolName
  changelog.md
  lib/pure/typetraits.nim
  lib/std/enumutils.nim
  tests/stdlib/tenumutils.nim
Labels: TODO: followup needed

#16067 fix #2844 #3911; add --spellsuggest to suggest symbols in scope with similar spellings on undefined symbol error
  changelog.md
  compiler/commands.nim
  compiler/lookups.nim
  compiler/options.nim
  compiler/semcall.nim
  doc/advopt.txt
  tests/misc/mspellsuggest.nim
  tests/misc/tspellsuggest.nim
  tests/misc/tspellsuggest2.nim
Labels: TODO: followup needed

#17398 fix #17393 getHomeDir and expandTilde should not include trailing `/`
  changelog.md
  lib/pure/os.nim
Labels: TODO: followup needed

#17339 Clarify behaviour of char replace
  lib/pure/strutils.nim
Labels: merge_when_passes_CI

#17432 Close #8545 by add a test case
  tests/misc/t8545.nim
Labels: merge_when_passes_CI

#17365 Improve jsre
  changelog.md
  lib/js/jsre.nim
Labels: TODO: followup needed

#17465 hint:cc goes to stderr (like all other hints) instead of stdout
  changelog.md
  compiler/extccomp.nim
Labels: merge_when_passes_CI

#16182 add algorithm.merge
  changelog.md
  lib/pure/algorithm.nim
  tests/stdlib/talgorithm.nim
Labels: TODO: followup needed

#17463 remove {.compileTime.} for procs with NimNode: redundant because of `tfTriggersCompileTime`
  lib/core/macros.nim
  lib/pure/asyncmacro.nim
  lib/pure/htmlgen.nim
  lib/pure/json.nim
  lib/pure/sugar.nim
  lib/pure/xmltree.nim
Labels: merge_when_passes_CI

#17315 fix #17260 render `\` properly in nim doc, rst2html
  lib/packages/docutils/rst.nim
  lib/system.nim
  nimdoc/rst2html/expected/rst_examples.html
  tests/stdlib/trstgen.nim
Labels: TODO: followup needed

#17348 Fix #17199
  compiler/vmgen.nim
  tests/arc/tarcmisc.nim
  tests/stdlib/tisolation.nim
Labels: merge_when_passes_CI

#17500 followup custom literals
  compiler/condsyms.nim
  compiler/ic/packed_ast.nim
  compiler/lexer.nim
  doc/manual.rst
  tests/lexer/tcustom_numeric_literals.nim
  tests/lexer/tstrlits.nim
  tests/lexer/tunary_minus.nim
Labels: merge_when_passes_CI

#17513 nim: unbreak CI; testament: add allowedFailure logic for tests that may fail but should still run
  testament/categories.nim
  testament/important_packages.nim
  testament/testament.nim
Labels: TODO: followup needed

#17550 system: fix link in `delete` proc
  lib/system.nim
Labels: merge_when_passes_CI

#15450 Add a getter for all defined Sections in parsecfg
  changelog.md
  lib/pure/parsecfg.nim
  tests/stdlib/tparsecfg.nim
Labels: merge_when_passes_CI

#17544 remove docutils.nimble (not a real nimble package, and affected canonical imports)
  lib/packages/docutils/docutils.nimble
  lib/packages/docutils/docutils.nimble.old
  lib/packages/docutils/highlite.nim
  lib/packages/docutils/rst.nim
  lib/packages/docutils/rstast.nim
  lib/packages/docutils/rstgen.nim
Labels: TODO: followup needed

#17568 [std/uri]fix #17481
  lib/pure/uri.nim
  tests/stdlib/turi.nim
Labels: merge_when_passes_CI

#16000 Add hasDataBuffered to asyncnet
  changelog.md
  lib/pure/asyncnet.nim
Labels: TODO: followup needed

#13793 unify tuple expressions
  changelog.md
  compiler/condsyms.nim
  compiler/parser.nim
  compiler/renderer.nim
  compiler/vm.nim
  doc/astspec.txt
  tests/ast_pattern_matching.nim
  tests/astspec/tastspec.nim
  tests/compiler/tprefixmatches.nim
  tests/lexer/tunary_minus.nim
  tests/macros/tdumpast.nim
  tests/parser/tpostexprblocks.nim
  tests/parser/ttypemodifiers.nim
Labels: merge_when_passes_CI

#17559 add getPort to resolve Port(0)
  changelog.md
  lib/pure/asynchttpserver.nim
  testament/lib/stdtest/netutils.nim
  tests/stdlib/tasynchttpserver_transferencoding.nim
Labels: TODO: followup needed
