Repository nim-lang/Nim, pull requests merged in 2021-04, with the labels that each got.

#17588 Fix #17017 (math edge cases)
  lib/pure/math.nim
  tests/stdlib/tmath.nim
Labels: TODO: followup needed

#17612 [docs minor] close #16553
  lib/pure/os.nim
Labels: TODO: followup needed

#17625 Improve the `typeinfo` module
  lib/core/typeinfo.nim
Labels: TODO: followup needed, merge_when_passes_CI

#17676 Update `sysrand` documentation
  doc/lib.rst
  lib/std/sysrand.nim
Labels: merge_when_passes_CI

#17671 Fix rst typo
  lib/core/typeinfo.nim
Labels: merge_when_passes_CI

#17695 IC: integrity checking
  compiler/ic/bitabs.nim
  compiler/ic/ic.nim
  compiler/ic/integrity.nim
  compiler/main.nim
  compiler/semdata.nim
  compiler/semstmts.nim
  koch.nim
  testament/categories.nim
Labels: merge_when_passes_CI

#17698 IC: added tcompiletime_counter test case
  tests/ic/mcompiletime_counter.nim
  tests/ic/tcompiletime_counter.nim
Labels: merge_when_passes_CI

#17709 Remove the use of usrToCell in gcMark [backport:1.2]
  lib/system/gc.nim
  lib/system/gc_ms.nim
Labels: merge_when_passes_CI

#11526 getCustomPragma is split up in more usable chunks
  changelog.md
  lib/core/macros.nim
  tests/pragmas/tcustom_pragma.nim
Labels: Feature, Next release

#17706 `import foo {.all.}` reboot
  changelog.md
  compiler/ast.nim
  compiler/ic/ic.nim
  compiler/ic/rodfiles.nim
  compiler/importer.nim
  compiler/lookups.nim
  compiler/magicsys.nim
  compiler/modulegraphs.nim
  compiler/modules.nim
  compiler/nimeval.nim
  compiler/options.nim
  compiler/semdata.nim
  compiler/semmagic.nim
  compiler/semstmts.nim
  compiler/semtypes.nim
  compiler/suggest.nim
  compiler/wordrecg.nim
  lib/std/importutils.nim
  testament/categories.nim
  tests/ic/mimports.nim
  tests/ic/mimportsb.nim
  tests/ic/timports.nim
  tests/importalls/m1.nim
  tests/importalls/m2.nim
  tests/importalls/m3.nim
  tests/importalls/m4.nim
  tests/importalls/mt0.nim
  tests/importalls/mt1.nim
  tests/importalls/mt2.nim
  tests/importalls/mt3.nim
  tests/importalls/mt4.nim
  tests/importalls/mt4b.nim
  tests/importalls/mt5.nim
  tests/importalls/mt6.nim
  tests/importalls/mt7.nim
  tests/importalls/mt8.nim
  tests/importalls/mt9.nim
  tests/importalls/tmain2.nim
Labels: TODO: followup needed

#17731 std/hashes: hash(ref|ptr|pointer) + other improvements
  lib/pure/hashes.nim
  testament/lib/stdtest/testutils.nim
  tests/collections/ttables.nim
  tests/stdlib/thashes.nim
  tests/stdlib/tstrutils.nim
Labels: TODO: followup needed

#17753 replace defer with try ... finally
  lib/core/rlocks.nim
  tests/stdlib/tuserlocks.nim
Labels: merge_when_passes_CI

#17752 fix #17749 ignore SIGPIPE signals, fix nim CI #17748
  changelog.md
  koch.nim
  lib/system/excpt.nim
  tests/stdlib/tosproc.nim
  tests/system/tsigexitcode.nim
Labels: TODO: followup needed

#17780 fix #17732(forward args... to megatest)
  testament/categories.nim
Labels: merge_when_passes_CI

#17781 Rename `=` to `=copy` in stdlib
  lib/deprecated/pure/sharedstrings.nim
  lib/std/channels.nim
  lib/std/isolation.nim
  lib/system.nim
  lib/system/widestrs.nim
Labels: merge_when_passes_CI

#17794 followup #16714: add -d:nimLegacyUnarySlice + changelog
  changelog.md
  lib/system.nim
Labels: merge_when_passes_CI

#17800 [std/deques] move data instead of copy + destroy
  lib/pure/collections/deques.nim
Labels: merge_when_passes_CI

#17799 [std/tasks]add gcsafe pragmas
  lib/std/tasks.nim
Labels: merge_when_passes_CI

#17361 close #9372 add std/tempfiles
  changelog.md
  lib/std/tempfiles.nim
  tests/stdlib/ttempfiles.nim
Labels: TODO: followup needed

#17746 `--filenames:abs|canonical|legacyRelProj` for filenames in compiler msgs (replaces `--listfullpaths:on|off`)
  changelog.md
  compiler/commands.nim
  compiler/docgen.nim
  compiler/main.nim
  compiler/msgs.nim
  compiler/options.nim
  doc/advopt.txt
  drnim/drnim.nim
  tests/config.nims
Labels: TODO: followup needed

#17774 fix #7535(Poor error message for spawn when a procedure (without calling it))
  compiler/semexprs.nim
  tests/parallel/t7535.nim
Labels: TODO: followup needed

#17817 add `--processing:dots|filenames|off` to customize `hintProcessing`
  changelog.md
  compiler/ccgtypes.nim
  compiler/commands.nim
  compiler/msgs.nim
  compiler/options.nim
  compiler/passaux.nim
  doc/advopt.txt
  drnim/tests/config.nims
  nimsuggest/config.nims
  nimsuggest/tester.nim
  nimsuggest/tests/tchk1.nim
  nimsuggest/tests/tchk_compiles.nim
  nimsuggest/tests/ttempl_inst.nim
  testament/testament.nim
  tests/misc/trunner.nim
Labels: PTAL

#17815 refactor all code that builds csources
  .builds/freebsd.yml
  .builds/openbsd_0.yml
  .builds/openbsd_1.yml
  .github/workflows/ci.yml.disabled
  .github/workflows/ci_docs.yml
  .github/workflows/ci_packages.yml
  .gitignore
  .travis.yml
  appveyor.yml.disabled
  azure-pipelines.yml
  build_all.bat
  build_all.sh
  ci/build.bat
  ci/build.sh
  ci/deps.bat
  ci/deps.sh
  ci/funs.sh
  ci/nsis_build.bat
  koch.nim
  lib/std/private/globs.nim
  readme.md
  tools/ci_generate.nim
Labels: TODO: followup needed, merge_when_passes_CI

#17811 manual: fix rendering of Identifiers & Keywords
  doc/manual.rst
Labels: PTAL

#17807 `typeof(voidStmt)` now works
  changelog.md
  compiler/condsyms.nim
  compiler/sem.nim
  compiler/semdata.nim
  compiler/semexprs.nim
  lib/js/asyncjs.nim
  testament/lib/stdtest/testutils.nim
  tests/typerel/tvoid.nim
Labels: PTAL

#17829 `--usenimcache` (implied by `nim r main`) now caches some compile options to avoid recompiling when project was previously compiled with such options.
  changelog.md
  compiler/extccomp.nim
  compiler/main.nim
  compiler/options.nim
  tests/misc/mbetterrun.nim
  tests/misc/trunner.nim
Labels: PTAL, TODO: followup needed

#17862 fix #17859; rename tests so they run in CI; merge several tests with nim check
  tests/errmsgs/tundeclared_routine.nim
  tests/errmsgs/tundeclared_routine_compiles.nim
  tests/errmsgs/undeclared_routine.nim
  tests/errmsgs/undeclared_routine2.nim
  tests/errmsgs/undeclared_routine3.nim
  tests/errmsgs/undeclared_routine4.nim
  tests/errmsgs/undeclared_routine5.nim
Labels: PTAL

#17875 externalToLink: use quoteShell to avoid issues with spaces in paths for {.link.} pragmas
  compiler/extccomp.nim
Labels: PTAL

#17887 fix #17853 (ascii message separator broke json nim dump)
  changelog.md
  compiler/main.nim
  compiler/msgs.nim
  compiler/options.nim
  tests/misc/trunner.nim
  tests/osproc/treadlines.nim
Labels: merge_when_passes_CI

#17889 fix #17888: remove undefined behavior for posix.open; fix tempfiles.createTempFile
  lib/posix/posix.nim
  lib/pure/streams.nim
  lib/std/tempfiles.nim
Labels: PTAL

#17879 improve nimsuggest/tester, minor improvements to koch.nim
  koch.nim
  nimdoc/testproject/testproject.nim
  nimpretty/tester.nim
  nimsuggest/tester.nim
Labels: PTAL

#17876 improve tsets.nim, twrong_setconstr.nim and avoid name clashes with compiler sets
  tests/ccgbugs/twrong_setconstr.nim
  tests/sets/tsets.nim
Labels: PTAL

#17892 gitutils: add diffStrings, diffFiles, and use it in testament to compare expected vs gotten
  lib/experimental/diff.nim
  lib/std/private/gitutils.nim
  lib/std/tempfiles.nim
  nimdoc/rsttester.nim
  nimdoc/tester.nim
  nimpretty/tester.nim
  testament/categories.nim
  testament/testament.nim
Labels: PTAL

#17895 close #16646; `since` now works with bootstrap nim post csources_v1
  compiler/semtypes.nim
  lib/packages/docutils/rst.nim
  tests/stdlib/trstgen.nim
Labels: PTAL, TODO: followup needed

#17902 bring back std/ prefix within compiler and ensure it works in bootstrap + bsd
  .builds/freebsd.yml
  .builds/openbsd_0.yml
  .builds/openbsd_1.yml
  compiler/ic/dce.nim
  compiler/vmops.nim
  koch.nim
  tools/ci_generate.nim
Labels: PTAL
