Repository nim-lang/Nim, pull requests merged in 2021-06, with the labels that each got.

#18082 fix #16993, #18054, #17835 runnableExamples now works with templates and nested templates
  compiler/evaltempl.nim
  lib/system/assertions.nim
  nimdoc/testproject/expected/subdir/subdir_b/utils.html
  nimdoc/testproject/expected/testproject.html
  nimdoc/testproject/subdir/subdir_b/utils.nim
  tests/js/tstdlib_various.nim
  tests/nimdoc/trunnableexamples.nim
  tests/nimdoc/trunnableexamples2.nim
Labels: PTAL

#18100 simplify extccomp.nim json logic via jsonutils; fix #18084
  compiler/extccomp.nim
  compiler/nimconf.nim
  compiler/options.nim
  lib/std/jsonutils.nim
Labels: PTAL

#18168 fix #7295: use move(result) inside template to avoid copy with --gc:refc
  lib/pure/collections/sequtils.nim
Labels: merge_when_passes_CI

#18072 macros.treeRepr + friends: collapse SymChoice
  changelog.md
  lib/core/macros.nim
  tests/macros/tdumpast.nim
  tests/stdlib/tmacros.nim
Labels: PTAL

#18183 up to 20x faster jsonutils deserialization
  lib/std/jsonutils.nim
Labels: Performance

#18179 fix #18178, set a CI timeout for github action pipelines instead of the 6 hour default
  .github/workflows/ci_docs.yml
  .github/workflows/ci_packages.yml
Labels: PTAL

#18197 make changeDetectedViaJsonBuildInstructions warning less verbose when json file invalid (eg due to spec change)
  compiler/extccomp.nim
Labels: PTAL

#18224 update .github/ISSUE_TEMPLATE/bug_report.md, mention PRs, contributing, devel branch
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: PTAL

#18222 avoid re-exporting `options` from std/wrapnils
  lib/std/wrapnils.nim
  tests/stdlib/twrapnils.nim
Labels: PTAL

#17546 fix #9437(fix `re.replace` wrong behaviour)
  lib/impure/re.nim
  tests/stdlib/tre.nim
Labels: TODO: followup needed

#18241 getType now works with tyInferred (arising from concepts); refs #18220
  compiler/vmdeps.nim
  tests/macros/tgettype.nim
Labels: PTAL

#18248 fix #7717 roundtrip float to string; fix `parseFloat` for js
  lib/system/jssys.nim
  tests/float/tfloat6.nim
  tests/float/tfloats.nim
Labels: PTAL

#15201 Improve httpClient docs on SSL cert verification
  lib/pure/httpclient.nim
Labels: S: Waiting on author

#18259 followup #17777: declaredloc field error msgs now work with generics
  compiler/astmsgs.nim
  compiler/semcall.nim
  tests/errmsgs/tundeclared_field.nim
Labels: PTAL

#18252 merge BuildMode into SuccessX, remove code duplication w drnim, add useful info to successx, add gc to compilesettings
  compiler/lineinfos.nim
  compiler/main.nim
  compiler/msgs.nim
  compiler/options.nim
  compiler/vmops.nim
  doc/nimc.rst
  drnim/drnim.nim
  lib/std/compilesettings.nim
  testament/testament.nim
  tests/misc/trunner.nim
Labels: PTAL, TODO: followup needed

#18249 fixes #18235 - proc annotation type macro sym leak
  compiler/lookups.nim
  compiler/semstmts.nim
  tests/macros/m18235.nim
  tests/macros/t18235.nim
Labels: CPS

#18195 Enable parallel build in build.sh
  tools/niminst/buildsh.nimf
Labels: Installation, Performance, Tools

#18247 system/excpt: check if the exception is not nil before pop
  lib/system/excpt.nim
  tests/exception/tsetexceptions.nim
Labels: CPS

#18266 add test case for pure enum redefinition error within enum (fixed in recent PR)
  compiler/astalgo.nim
  compiler/lookups.nim
  tests/errmsgs/t10251.nim
Labels: PTAL

#18282 followup #16400; use use -d:nimCompilerStackraceHints in more places
  compiler/vmgen.nim
Labels: Easy, PTAL

#18281 increase backoffDuration to avoid timeouts
  testament/categories.nim
Labels: Easy, PTAL

#18264 make tests/exception/tsetexceptions.nim not joinable (because of `setCurrentException(nil)`)
  tests/exception/tsetexceptions.nim
Labels: PTAL

#18243 add more APIs to compiler/debugutils to help debugging compiler
  compiler/debugutils.nim
  compiler/options.nim
  compiler/semexprs.nim
  tests/compiler/tdebugutils.nim
Labels: PTAL

#18274 strformat.fmt now supports non-literal const strings
  changelog.md
  lib/core/macros.nim
  lib/pure/strformat.nim
Labels: merge_when_passes_CI

#18290 refs #18278: do not gag fatal msgs
  compiler/lineinfos.nim
  compiler/modules.nim
  compiler/msgs.nim
  compiler/pragmas.nim
Labels: PTAL

#18260 make privateAccess work with generic types and generic instantiations; fix a SIGSEGV
  compiler/ast.nim
  compiler/semmagic.nim
  lib/std/importutils.nim
  tests/stdlib/mimportutils.nim
  tests/stdlib/timportutils.nim
Labels: merge_when_passes_CI

#18299 testutils.assertAll: show correct location on assert failure
  testament/lib/stdtest/testutils.nim
Labels: Easy, PTAL

#18293 add `typetraits.pointerBase` to return `T` in `ref T|ptr T`
  changelog.md
  lib/pure/typetraits.nim
Labels: PTAL

#18256 docgen: move to shared RST state (fix #16990)
  compiler/commands.nim
  compiler/docgen.nim
  compiler/docgen2.nim
  compiler/main.nim
  compiler/options.nim
  lib/packages/docutils/rst.nim
  nimdoc/testproject/expected/subdir/subdir_b/utils.idx
  tests/stdlib/trstgen.nim
Labels: TODO: followup needed

#18300 move {.injectStmt.} to experimental; add a test
  compiler/pragmas.nim
  doc/manual.rst
  doc/manual_experimental.rst
  lib/pure/asyncdispatch.nim
  lib/system/gc_ms.nim
  tests/pragmas/tinjectstmt.nim
Labels: Easy, PTAL

#17852 support `--hint:all:off --hint:x` (ditto with `--warnings` + friends)
  changelog.md
  compiler/commands.nim
  compiler/condsyms.nim
  doc/advopt.txt
  tests/misc/trunner.nim
Labels: PTAL

#18311 followup #17852, disallow all:on for now for hint + friends
  compiler/commands.nim
  doc/advopt.txt
Labels: PTAL

#18317 fixes #17768 [backport:1.4]
  lib/pure/unicode.nim
  tests/stdlib/tunicode.nim
Labels: TODO: followup needed

#18316 close #13196 (json roundtrip) now that we have dragonbox
  tests/stdlib/tjson.nim
  tests/stdlib/tjsonutils.nim
Labels: merge_when_passes_CI

#18318 merge similar procs regarding digits
  lib/std/private/digitsutils.nim
  lib/system/dollars.nim
  lib/system/dragonbox.nim
  lib/system/schubfach.nim
  lib/system/strmantle.nim
Labels: PTAL

#18330 followup #18318: simplify `dollarImpl` and add a test
  lib/system/dollars.nim
  tests/stdlib/tdigitsutils.nim
Labels: PTAL

#17901 [std/times]getTime now uses high resolution API on windows
  lib/pure/times.nim
  lib/windows/winlean.nim
Labels: PTAL

#18336 fix #18332: XDeclaredButNotUsed hints now in deterministic order
  compiler/lookups.nim
  tests/errmsgs/treportunused.nim
Labels: PTAL

#18337 fix #18334: handle path with spaces on windows during bootstrap
  compiler/nim.nim
  koch.nim
Labels: merge_when_passes_CI

#18244 enable VM tracing in user code via `{.define(nimVmTrace).}`
  changelog.md
  compiler/options.nim
  compiler/vm.nim
  compiler/vmops.nim
  lib/std/vmutils.nim
  tests/stdlib/tvmutils.nim
Labels: PTAL

#18344 couple tiny typo fixes in std/times
  lib/pure/times.nim
Labels: merge_when_passes_CI

#18345 docs now show nimExperimentalX APIs
  lib/std/jsfetch.nim
  lib/wrappers/linenoise/linenoise.nim
  tests/config.nims
  tools/kochdocs.nim
Labels: PTAL

#18353 ensure 'koch boot --gc:orc' stays green
  koch.nim
Labels: merge_when_passes_CI

#18362 even lighter version of #17938: fix most issues with UnusedImport, XDeclaredButNotUsed, etc; fix #17511, #17510, #14246 (without realModule)
  compiler/importer.nim
  compiler/lineinfos.nim
  compiler/lookups.nim
  compiler/passaux.nim
  lib/system/schubfach.nim
  testament/categories.nim
  tests/deprecated/tmodule1.nim
  tests/modules/tselfimport.nim
  tests/pragmas/mused2a.nim
  tests/pragmas/mused2b.nim
  tests/pragmas/mused2c.nim
  tests/pragmas/tused2.nim
  tests/statictypes/tstatictypes.nim
Labels: PTAL, TODO: followup needed

#18366 followup #18362: make `UnusedImport` work robustly
  compiler/cgen.nim
  compiler/dfa.nim
  compiler/docgen.nim
  compiler/importer.nim
  compiler/injectdestructors.nim
  compiler/jsgen.nim
  compiler/lineinfos.nim
  compiler/lookups.nim
  compiler/semdata.nim
  compiler/suggest.nim
  tests/misc/trunner.nim
  tests/pragmas/mused3.nim
  tests/pragmas/mused3a.nim
  tests/pragmas/mused3b.nim
Labels: PTAL

#18289 `./koch tools` now builds `bin/nim_dbg`, a debug version of nim
  koch.nim
  tools/kochdocs.nim
Labels: PTAL

#18377 Fix #16426
  compiler/parser.nim
  tests/parser/tstmtlists.nim
Labels: merge_when_passes_CI

#18379 Cleanup lookups.nim again..
  compiler/lookups.nim
Labels: merge_when_passes_CI

#18382 simplify rdstdin
  lib/impure/rdstdin.nim
Labels: Easy, merge_when_passes_CI

#18372 improvements to hint:processing: show import stack, distinguish nims, show includes etc
  compiler/lineinfos.nim
  compiler/modulegraphs.nim
  compiler/modules.nim
  compiler/passaux.nim
  compiler/semstmts.nim
  nimsuggest/tests/tchk1.nim
  nimsuggest/tests/tchk_compiles.nim
  nimsuggest/tests/ttempl_inst.nim
Labels: PTAL
