Repository nim-lang/Nim, pull requests merged in 2021-07, with the labels that each got.

#18406 don't use `{.rtl.}` for generics, otherwise `-d:useNimRtl` gives `ambiguous identifier` nimrtl error
  lib/pure/strutils.nim
  lib/system/inclrtl.nim
  tests/dll/client.nim
Labels: TODO: followup needed

#18435 major improvements to `std/wrapnils`: optimal codegen, case objects, lvalue semantics
  changelog.md
  lib/std/wrapnils.nim
  tests/stdlib/twrapnils.nim
Labels: PTAL

#18440 ORC: use =destroy instead of =dispose
  compiler/ast.nim
  compiler/ccgtypes.nim
  compiler/liftdestructors.nim
  compiler/semstmts.nim
  doc/manual.rst
  lib/system.nim
  lib/system/cellseqs_v2.nim
  lib/system/cyclebreaker.nim
  lib/system/orc.nim
  tests/arc/thamming_orc.nim
Labels: merge_when_passes_CI

#18443 improve rendering of newOSError.additionalInfo
  lib/pure/includes/oserr.nim
  lib/pure/net.nim
Labels: PTAL

#18451 followup #18252: show special flags -d:danger, -d:release when given
  compiler/msgs.nim
Labels: PTAL

#18389 improve `--declaredLocs` to help disambiguate types (generics, aliases etc)
  changelog.md
  compiler/astmsgs.nim
  compiler/semcall.nim
  compiler/semexprs.nim
  compiler/types.nim
  tests/errmsgs/tdeclaredlocs.nim
  tests/errmsgs/tproc_mismatch.nim
  tests/errmsgs/tsigmatch.nim
Labels: PTAL

#18457 runnableExamples now show originating location in stacktraces on failure
  compiler/docgen.nim
  compiler/renderverbatim.nim
Labels: PTAL

#18459 ORC: support for custom =trace procs
  changelog.md
  compiler/ast.nim
  compiler/ccgexprs.nim
  compiler/condsyms.nim
  compiler/jsgen.nim
  compiler/liftdestructors.nim
  compiler/semmagic.nim
  compiler/semstmts.nim
  compiler/vmgen.nim
  doc/destructors.rst
  doc/manual.rst
  lib/system.nim
  tests/arc/tcustomtrace.nim
Labels: merge_when_passes_CI

#12104 Add changes required by Nimble lock file support
  compiler/modulepaths.nim
  compiler/nimblecmd.nim
  lib/std/sha1.nim
  tests/compiler/tnimblecmd.nim
  tests/stdlib/tsha1.nim
Labels: Postponed

#18501 fix #18142: nim doc now works across windows partitions (and make `nativeToUnixPath` work with abs paths)
  lib/std/private/globs.nim
  tests/stdlib/tglobs.nim
Labels: PTAL

#18512 add NIM_STATIC_ASSERT(CHAR_BIT == 8, "") to fail-fast where assumption is violated
  lib/nimbase.h
Labels: PTAL

#18510 deprecate strutils.delete and add an overload with saner semantics consistent with sequtils.delete; follows #18487
  changelog.md
  lib/pure/strutils.nim
  tests/stdlib/tstrutils.nim
Labels: PTAL

#18514 attempt to support short commit hashes
  tools/atlas/atlas.nim
Labels: merge_when_passes_CI

#18515 nim doc now correctly renders deprecated pragmas for routines and types
  compiler/ast.nim
  compiler/docgen.nim
  compiler/renderer.nim
  nimdoc/testproject/expected/testproject.html
  nimdoc/testproject/expected/testproject.idx
  nimdoc/testproject/expected/theindex.html
  nimdoc/testproject/testproject.nim
Labels: PTAL

#18542 use more `.}`
  changelogs/changelog_0_19_0.md
  doc/manual_experimental.rst
  lib/posix/posix_linux_amd64.nim
  lib/system.nim
  lib/windows/winlean.nim
Labels: merge_when_passes_CI

#18531 make -d:nimFpRoundtrips work consistently in vm vs rt, fix #18400, etc
  compiler/ast.nim
  compiler/ccgexprs.nim
  compiler/jsgen.nim
  compiler/nim.cfg
  compiler/rodutils.nim
  compiler/semfold.nim
  compiler/vmgen.nim
  compiler/vmhooks.nim
  compiler/vmops.nim
  lib/system.nim
  lib/system/dollars.nim
  lib/system/formatfloat.nim
  lib/system/jssys.nim
  lib/system/repr_v2.nim
  lib/system/strmantle.nim
  tests/config.nims
  tests/errmsgs/treportunused.nim
  tests/float/nim.cfg
  tests/float/tfloats.nim
  tests/stdlib/tjson.nim
  tests/stdlib/tjsonutils.nim
Labels: PTAL

#18544 fixes #18469
  compiler/injectdestructors.nim
  compiler/jsgen.nim
  compiler/types.nim
  tests/arc/tcursor_field_obj_constr.nim
Labels: merge_when_passes_CI

#18456 std/random: fix overflow bugs #16360 #16296 #17670
  lib/pure/random.nim
  tests/stdlib/trandom.nim
Labels: PTAL

#18566 rename nimFpRoundtrips => nimPreviewFloatRoundtrip
  changelog.md
  compiler/nim.cfg
  lib/system/formatfloat.nim
  tests/config.nims
  tests/errmsgs/treportunused.nim
  tests/float/tfloats.nim
Labels: merge_when_passes_CI

#18567 refactoring: removed dead code `efAllowDestructor`
  compiler/semdata.nim
  compiler/semexprs.nim
  compiler/semobjconstr.nim
  compiler/semstmts.nim
Labels: merge_when_passes_CI

#18587 Optimize for the non-throwing case
  lib/pure/collections/tables.nim
Labels: merge_when_passes_CI

#17356 Update documentation for dynlib
  lib/pure/dynlib.nim
Labels: TODO: followup needed

#18598 Fixed const tuples in inferred generics
  compiler/semgnrc.nim
  tests/tuples/tinferred_generic_const.nim
Labels: merge_when_passes_CI

#18594 add comment field to astalgo.debug
  compiler/astalgo.nim
Labels: merge_when_passes_CI

#18568 delEnv now works at CT
  compiler/vmops.nim
Labels: PTAL

#18599 fixes #18570
  compiler/injectdestructors.nim
Labels: merge_when_passes_CI

#18600 fixes #18579
  lib/system/arc.nim
  tests/arc/tunref_cycle.nim
Labels: merge_when_passes_CI

#18595 support same-line doc comments in routines
  compiler/parser.nim
  nimdoc/testproject/expected/subdir/subdir_b/utils.html
  nimdoc/testproject/expected/subdir/subdir_b/utils.idx
  nimdoc/testproject/expected/theindex.html
  nimdoc/testproject/subdir/subdir_b/utils.nim
  tests/stdlib/trepr.nim
Labels: PTAL

#18590 fix #17072: add times.dateTime with ISO 8601 order
  changelog.md
  lib/pure/times.nim
Labels: PTAL

#18575 Remove tracking of environment from osenv.nim v2
  changelog.md
  lib/pure/includes/osenv.nim
  lib/std/private/win_setenv.nim
  tests/destructor/tnewruntime_misc.nim
  tests/stdlib/tos.nim
  tests/stdlib/tosenv.nim
Labels: PTAL

#18581 fix #18385 followup, by building nimsuggest with -d:release during testing
  koch.nim
  nimsuggest/tester.nim
Labels: PTAL

#18613 refs #16613: check opcWrDeref for nil
  compiler/vm.nim
Labels: PTAL
