Repository nim-lang/Nim, pull requests merged in 2021-02, with the labels that each got.

#16992 nep1: prefer `a..b` to `a .. b` except if `b` has an operator (eg: `a .. -1`)
  doc/nep1.rst
Labels: vote

#17031 Better error message for rand(153 .. 102)
  lib/pure/random.nim
Labels: merge_when_passes_CI

#17065 nep1: triple quote literals should start with newline
  doc/nep1.rst
Labels: vote

#17066 Add setutils.complement, setutils.fullSet
  changelog.md
  lib/std/setutils.nim
  tests/stdlib/tsetutils.nim
Labels: merge_when_passes_CI

#17064 uri: document removeDotSegments, add tests, show failure modes
  lib/pure/uri.nim
  tests/stdlib/turi.nim
Labels: TODO: followup needed

#17135 [std/json]remove unnecessary when statement
  lib/pure/json.nim
  tests/stdlib/tjson.nim
Labels: TODO: followup needed

#16609 make copySign for js consistent with other backends
  lib/pure/math.nim
  tests/stdlib/tmath.nim
  tests/vm/tcastint.nim
Labels: TODO: followup needed

#17143 when statements branches exit early
  compiler/semexprs.nim
  tests/whenstmt/twhen.nim
  tests/whenstmt/twhen_macro.nim
Labels: merge_when_passes_CI

#17132 remove tests/deps/
  compiler/condsyms.nim
  compiler/nimpaths.nim
  doc/testament.rst
  koch.nim
  testament/lib/stdtest/specialpaths.nim
  testament/specs.nim
  tests/cpp/tasync_cpp.nim
  tests/deps/jester-#head/jester.nim
  tests/deps/jester-#head/jester.nimble
  tests/deps/jester-#head/jester/patterns.nim
  tests/deps/jester-#head/jester/private/errorpages.nim
  tests/deps/jester-#head/jester/private/utils.nim
  tests/deps/jester-#head/jester/request.nim
  tests/deps/opengl-1.1.0/glu.nim
  tests/deps/opengl-1.1.0/glut.nim
  tests/deps/opengl-1.1.0/glx.nim
  tests/deps/opengl-1.1.0/opengl.nim
  tests/deps/opengl-1.1.0/opengl.nimble
  tests/deps/opengl-1.1.0/wingl.nim
  tests/deps/x11-1.0/cursorfont.nim
  tests/deps/x11-1.0/keysym.nim
  tests/deps/x11-1.0/x.nim
  tests/deps/x11-1.0/x11.nimble
  tests/deps/x11-1.0/x11pragma.nim
  tests/deps/x11-1.0/xatom.nim
  tests/deps/x11-1.0/xcms.nim
  tests/deps/x11-1.0/xf86dga.nim
  tests/deps/x11-1.0/xf86vmode.nim
  tests/deps/x11-1.0/xi.nim
  tests/deps/x11-1.0/xinerama.nim
  tests/deps/x11-1.0/xkb.nim
  tests/deps/x11-1.0/xkblib.nim
  tests/deps/x11-1.0/xlib.nim
  tests/deps/x11-1.0/xrandr.nim
  tests/deps/x11-1.0/xrender.nim
  tests/deps/x11-1.0/xresource.nim
  tests/deps/x11-1.0/xshm.nim
  tests/deps/x11-1.0/xutil.nim
  tests/deps/x11-1.0/xv.nim
  tests/deps/x11-1.0/xvlib.nim
  tests/deps/zip-0.2.1/zip.nimble
  tests/deps/zip-0.2.1/zip/gzipfiles.nim
  tests/deps/zip-0.2.1/zip/libzip.nim
  tests/deps/zip-0.2.1/zip/private/libzip_all.c
  tests/deps/zip-0.2.1/zip/zipfiles.nim
  tests/deps/zip-0.2.1/zip/zlib.nim
  tests/deps/zip-0.2.1/zip/zzip.nim
  tests/manyloc/keineschweine/lib/zlib_helpers.nim
  tools/kochdocs.nim
Labels: TODO: followup needed

#17063 document type bound operators
  doc/destructors.rst
  doc/manual.rst
Labels: TODO: followup needed

#17080 add enumutils.items for sparse enums, typetraits.SomeSparseEnum
  changelog.md
  doc/lib.rst
  lib/pure/typetraits.nim
  lib/std/enumutils.nim
  lib/system/iterators.nim
  tests/stdlib/tenumutils.nim
Labels: TODO: followup needed, vote

#15251 new-style concepts implementation, WIP
  compiler/ast.nim
  compiler/concepts.nim
  compiler/jsgen.nim
  compiler/liftdestructors.nim
  compiler/parser.nim
  compiler/sem.nim
  compiler/semdata.nim
  compiler/seminst.nim
  compiler/semstmts.nim
  compiler/semtypes.nim
  compiler/semtypinst.nim
  compiler/sigmatch.nim
  compiler/typeallowed.nim
  compiler/types.nim
  compiler/vmdeps.nim
  tests/concepts/tconcepts.nim
  tests/concepts/tconcepts_issues.nim
  tests/concepts/tconcepts_overload_precedence.nim
  tests/concepts/tspec.nim
Labels: merge_when_passes_CI

#17160 fix #17159 items(cstring) works in VM
  lib/system/iterators.nim
  testament/lib/stdtest/testutils.nim
  tests/arc/tcstring.nim
  tests/stdlib/tcstring.nim
Labels: TODO: followup needed

#16931 wrapnils: add `??.` which returns an `Option`
  changelog.md
  lib/std/wrapnils.nim
  tests/stdlib/twrapnils.nim
Labels: merge_when_passes_CI

#17171 fixes #17170
  compiler/ccgcalls.nim
  compiler/closureiters.nim
  tests/arc/torcmisc.nim
Labels: merge_when_passes_CI

#16871 asyncjs: add `then`, `catch` for promise pipelining
  changelog.md
  compiler/nim.nim
  lib/js/asyncjs.nim
  testament/testament.nim
  tests/config.nims
  tests/js/tasync.nim
  tests/js/tasyncjs_fail.nim
Labels: TODO: followup needed

#17147 `std/options`: `$some(3)` is now `"some(3)"`, etc.
  changelog.md
  lib/pure/options.nim
  testament/important_packages.nim
  tests/generics/tgenerics_issues.nim
  tests/stdlib/tmarshal.nim
  tests/stdlib/toptions.nim
Labels: TODO: followup needed

#17181 use single backtick
  lib/pure/base64.nim
  lib/pure/dynlib.nim
  lib/pure/fenv.nim
  lib/pure/htmlgen.nim
  lib/pure/htmlparser.nim
  lib/pure/httpclient.nim
  lib/pure/nimprof.nim
  lib/pure/oswalkdir.nim
  lib/pure/parsecfg.nim
  lib/pure/parsesql.nim
Labels: merge_when_passes_CI

#17202 Change stdlib imports to use std prefix in most examples
  doc/hcr.rst
  doc/manual.rst
  doc/spawn.txt
  lib/core/macros.nim
  lib/impure/db_mysql.nim
  lib/impure/db_odbc.nim
  lib/impure/db_postgres.nim
  lib/impure/db_sqlite.nim
  lib/impure/nre.nim
  lib/impure/re.nim
  lib/posix/posix.nim
  lib/posix/posix_utils.nim
  lib/pure/asyncfile.nim
  lib/pure/asyncftpclient.nim
  lib/pure/asynchttpserver.nim
  lib/pure/asyncnet.nim
  lib/pure/base64.nim
  lib/pure/cgi.nim
  lib/pure/collections/critbits.nim
  lib/pure/collections/deques.nim
  lib/pure/collections/lists.nim
  lib/pure/collections/sequtils.nim
  lib/pure/collections/tables.nim
  lib/pure/dynlib.nim
  lib/pure/htmlparser.nim
  lib/pure/httpclient.nim
  lib/pure/json.nim
  lib/pure/logging.nim
  lib/pure/osproc.nim
  lib/pure/parsecfg.nim
  lib/pure/parsecsv.nim
  lib/pure/parseopt.nim
  lib/pure/parseutils.nim
  lib/pure/pegs.nim
  lib/pure/streams.nim
  lib/pure/streamwrapper.nim
  lib/pure/strscans.nim
  lib/pure/strutils.nim
  lib/pure/times.nim
  lib/std/jsonutils.nim
  lib/system.nim
  lib/system/channels.nim
  lib/system/io.nim
  lib/system/iterators_1.nim
  lib/system/threads.nim
Labels: merge_when_passes_CI
