Repository nim-lang/Nim, pull requests merged in 2021-09, with the labels that each got.

#18814 '[]' can now be used for iterators
  compiler/semexprs.nim
  tests/iter/tarrayiter.nim
Labels: merge_when_passes_CI

#18872 Revert "use new Nimble, with lockfiles (#18810)"
  koch.nim
Labels: merge_when_passes_CI

#18885 update csources hash
  config/build_config.txt
Labels: merge_when_passes_CI

#18890 arc: improve compile time of (nested) loops
  compiler/dfa.nim
Labels: merge_when_passes_CI, ARC/ORC

#18615 envPairs works in vm, nims
  compiler/vmops.nim
  lib/pure/includes/osenv.nim
  lib/pure/os.nim
  testament/lib/stdtest/testutils.nim
  tests/js/tos.nim
  tests/stdlib/tosenv.nim
  tests/test_nimscript.nims
Labels: PTAL

#18931 Alternative to #18928
  compiler/semtypinst.nim
  tests/generics/trecursivegenerics.nim
Labels: merge_when_passes_CI
