Repository nim-lang/Nim, pull requests merged in 2021-05, with the labels that each got.

#17908 Fix nim-lang/nimforum#285 - punctuation after URL
  lib/packages/docutils/rst.nim
  tests/stdlib/trst.nim
Labels: merge_when_passes_CI

#17896 misc fixes: remove `forceConst` (obsolete by static), add more runnableExamples to system
  lib/std/compilesettings.nim
  lib/system.nim
  tests/vm/tconst.nim
  tests/vm/tconsteval.nim
  tests/vm/tvmops.nim
Labels: PTAL

#17912 fix #17911 rawProc for cpp
  lib/pure/hashes.nim
  lib/system.nim
  tests/stdlib/thashes.nim
  tests/stdlib/tsystem.nim
Labels: PTAL

#17934 add logging to help investigate why tests/vm/tconst.nim is flaky
  tests/vm/tconst.nim
Labels: PTAL

#17939 docgen: get rid of ropes
  compiler/docgen.nim
Labels: merge_when_passes_CI

#17953 remove unsused OsPlatform.nimVM
  lib/system/platforms.nim
Labels: PTAL

#17944 fix #14873 properly by skipping `abi` field in importc type
  lib/core/locks.nim
  lib/system/syslocks.nim
  tests/stdlib/uselocks.nim
Labels: PTAL

#17954 fix tests/vm/tcastint.nim which used non-sensical `when defined nimVM` (and contained wrong tests)
  tests/vm/tcastint.nim
Labels: PTAL

#17961 add astmsgs; add `declared in` msg for usage lint errors
  compiler/ast.nim
  compiler/astmsgs.nim
  compiler/linter.nim
  compiler/lookups.nim
  compiler/msgs.nim
  compiler/sem.nim
  compiler/types.nim
  tests/stylecheck/tusages.nim
  tests/tools/tlinter.nim
Labels: PTAL

#17942 fix #17941: UnusedImport works for var/let/const/type invoked inside a generic
  compiler/semgnrc.nim
  lib/pure/base64.nim
  lib/pure/collections/deques.nim
  lib/system/platforms.nim
Labels: PTAL

#17947 testament :show duration also for failed tests; improve `tshould_not_work`; mitigate #17946 tchannels timeouts
  testament/lib/stdtest/testutils.nim
  testament/testament.nim
  testament/tests/shouldfail/tccodecheck.nim
  testament/tests/shouldfail/tcolumn.nim
  testament/tests/shouldfail/terrormsg.nim
  testament/tests/shouldfail/texitcode1.nim
  testament/tests/shouldfail/tfile.nim
  testament/tests/shouldfail/tline.nim
  testament/tests/shouldfail/tmaxcodesize.nim
  testament/tests/shouldfail/tnimout.nim
  testament/tests/shouldfail/tnimoutfull.nim
  testament/tests/shouldfail/toutput.nim
  testament/tests/shouldfail/toutputsub.nim
  testament/tests/shouldfail/treject.nim
  testament/tests/shouldfail/tsortoutput.nim
  testament/tests/shouldfail/ttimeout.nim
  testament/tests/shouldfail/tvalgrind.nim
  tests/misc/trunner.nim
  tests/stdlib/tchannels.nim
  tests/stdlib/ttestutils.nim
  tests/testament/tshould_not_work.nim
Labels: PTAL

#17968 make testament `isSuccess` more robust and allow tests with `--hints:off` to succeed
  testament/specs.nim
  testament/testament.nim
  tests/misc/thints_off.nim
  tests/statictypes/tstatictypes.nim
Labels: PTAL

#17468 fix #17467 1st call to rand is now non-skewed; allow seed == 0
  changelog.md
  lib/pure/random.nim
  testament/important_packages.nim
  tests/stdlib/trandom.nim
Labels: PTAL

#17920 improve std/tempfiles
  lib/std/tempfiles.nim
  lib/windows/winlean.nim
  tests/stdlib/ttempfiles.nim
Labels: PTAL

#17999 docs: fix syntax error in hotCodeReloading example
  doc/hcr.rst
Labels: merge_when_passes_CI

#18000 ORC: progress
  compiler/btrees.nim
  compiler/ccgtypes.nim
  compiler/dfa.nim
  compiler/liftdestructors.nim
  compiler/semdata.nim
  compiler/types.nim
  compiler/vm.nim
  compiler/vmdef.nim
  lib/std/packedsets.nim
  lib/system.nim
  lib/system/orc.nim
Labels: merge_when_passes_CI

#17777 more informative error msg for undeclared field (`A(badfield: 1)` and `a.badfield = expr`)
  compiler/semcall.nim
  compiler/semobjconstr.nim
  tests/errmsgs/tundeclared_field.nim
Labels: PTAL, TODO: followup needed

#18026 fix #18007: std/json now serializes nan,inf,-inf as strings instead of invalid json
  changelog.md
  lib/pure/json.nim
  lib/std/jsonutils.nim
  tests/stdlib/tjson.nim
  tests/stdlib/tjsonutils.nim
Labels: PTAL

#18036 ./koch --nonexistant now fails
  koch.nim
Labels: merge_when_passes_CI

#18062 close #5540 generic object with generic field evaluated too early
  tests/misc/t5540.nim
Labels: PTAL

#18078 Move async example to asynchronous version of proc
  lib/pure/httpclient.nim
Labels: merge_when_passes_CI

#18035 refactor common code in CI pipelines
  .builds/freebsd.yml
  .builds/openbsd_0.yml
  .builds/openbsd_1.yml
  .github/workflows/ci_docs.yml
  .github/workflows/ci_packages.yml
  azure-pipelines.yml
  ci/funs.sh
  tools/ci_generate.nim
Labels: PTAL

#18094 close #3482 no more cgen error with typed templates
  tests/misc/t3482.nim
Labels: PTAL

#18085 change `--hint[X] => --hint:X` in nim repo (avoids shell quoting issues)
  compiler/nim.cfg
  compiler/nimfix/nimfix.nim.cfg
  config/nim.cfg
  doc/advopt.txt
  doc/filters.rst
  doc/nimc.rst
  drnim/nim.cfg
  nimsuggest/nimsuggest.nim.cfg
  testament/categories.nim
  tests/effects/toutparam.nim
  tests/osproc/treadlines.nim
  tests/pragmas/t8741.nim
  tests/range/tcompiletime_range_checks.nim
  tests/tools/tunused_imports.nim
  tools/nimweb.nim
Labels: PTAL, TODO: followup needed

#18087 testament: remove deadcode related to realtimeGC, testC, callCCompiler
  testament/categories.nim
  testament/testament.nim
  tests/readme.md
  tests/realtimeGC/cmain.c
  tests/realtimeGC/readme.txt
  tests/realtimeGC/tmain.nim
Labels: PTAL

#18047 close #16569: deprecated `reversed(a, start, last)` overload, use toOpenArray instead
  changelog.md
  lib/pure/algorithm.nim
Labels: PTAL

#18107 revive Linux_i386; upgrade ubuntu 16.04 (not supported starting dec 2021) => 18.04
  .gitlab-ci.yml
  azure-pipelines.yml
Labels: PTAL

#18083 fix warnings/hints in nimdoc/tester.nim
  nimdoc/tester.nim
  nimdoc/testproject/expected/testproject.html
  nimdoc/testproject/testproject.nim
Labels: PTAL

#18106 document macros.unpackVarargs
  lib/core/macros.nim
  tests/destructor/tatomicptrs.nim
  tests/stdlib/tmacros.nim
Labels: PTAL

#18089 fix #16256: nimout: <empty> should give error (vacuously true); improve a few tests
  testament/specs.nim
  tests/misc/t9091.nim
  tests/misc/t9710.nim
  tests/stdlib/t9710.nim
  tests/stdlib/tgetprotobyname.nim
  tests/stdlib/tnativesockets.nim
  tests/stdlib/tvarints.nim
Labels: PTAL

#18097 jsonutils.toJson now serializes JsonNode as is by default
  changelog.md
  lib/std/jsonutils.nim
  tests/stdlib/tjsonutils.nim
Labels: PTAL
