Repository nim-lang/Nim, pull requests merged in 2022-08, with the labels that each got.

#20176 bootstrap the compiler with nimPreviewSlimSystem
  compiler/depends.nim
  compiler/docgen.nim
  compiler/jsgen.nim
  compiler/nim.cfg
  compiler/packages.nim
  compiler/renderverbatim.nim
  compiler/typesrenderer.nim
  compiler/vmops.nim
  lib/packages/docutils/dochelpers.nim
  lib/packages/docutils/highlite.nim
  lib/packages/docutils/rst.nim
  lib/packages/docutils/rstast.nim
  lib/packages/docutils/rstgen.nim
  lib/pure/collections/lists.nim
  lib/pure/strscans.nim
  lib/pure/uri.nim
  lib/pure/xmltree.nim
  lib/std/strbasics.nim
  lib/system/threads.nim
Labels: v2

#19488 make implicit cstring conversions explicit
  compiler/evalffi.nim
  compiler/tccgen.nim
  lib/impure/db_mysql.nim
  lib/impure/db_odbc.nim
  lib/impure/db_postgres.nim
  lib/impure/db_sqlite.nim
  lib/nimhcr.nim
  lib/pure/logging.nim
  lib/pure/nativesockets.nim
  lib/pure/net.nim
  lib/pure/os.nim
  lib/pure/osproc.nim
  lib/pure/parsejson.nim
  tools/nimblepkglist.nim
Labels: merge_when_passes_CI

#20222 Remove string == nil/nil == string error
  lib/system.nim
Labels: Requires Araq

#20163 fixes #20162; locals doesn't work with ORC [backport]
  compiler/plugins/locals.nim
  tests/misc/tlocals.nim
Labels: v2, Requires Araq

#20260 fixes doc building regression; trigger builds on markdown files
  .github/workflows/ci_docs.yml
Labels: merge_when_passes_CI

#19968 fixes #19967; reset does not work on set [backport: 1.2]
  compiler/ccgreset.nim
  tests/stdlib/tsystem.nim
Labels: TODO: followup needed, Ready For Review

#20109 remove `shallow` usages for ORC
  compiler/ccgtypes.nim
  compiler/msgs.nim
  lib/pure/asyncnet.nim
Labels: Requires Araq

#20250 remove unused nimfind defines
  compiler/modulegraphs.nim
Labels: Requires Araq

#20251 remove a special case in sigmatch; distinct pointer types no longer match `nil` type
  changelog.md
  compiler/sigmatch.nim
  tests/distinct/tnil.nim
  tests/errmsgs/tdistinct_nil.nim
Labels: Requires Araq

#20178 remove echo statements in tests (part 1)
  tests/vm/tfile_rw.nim
  tests/vm/tnewseqofcap.nim
  tests/vm/tquadplus.nim
  tests/vm/treset.nim
  tests/vm/triangle_array.nim
  tests/vm/tvarsection.nim
  tests/vm/twrong_concat.nim
  tests/vm/tyaytypedesc.nim
  tests/whenstmt/twhen_macro.nim
Labels: Requires Araq

#20201 remove {.this.} pragma, deprecated since 0.19
  changelog.md
  compiler/ast.nim
  compiler/pragmas.nim
  compiler/semcall.nim
  compiler/semdata.nim
  compiler/semexprs.nim
  compiler/seminst.nim
  tests/destructor/tcustomstrings.nim
  tests/misc/tcsharpusingstatement.nim
  tests/misc/tupcomingfeatures.nim
  tests/overload/tselfderef.nim
  tests/usingstmt/tthis.nim
  tests/usingstmt/tusingstmt.nim
Labels: Requires Araq

#20091 top-down type inference, implements rfc 149
  compiler/ast.nim
  compiler/ccgexprs.nim
  compiler/condsyms.nim
  compiler/jsgen.nim
  compiler/sem.nim
  compiler/semdata.nim
  compiler/semexprs.nim
  compiler/semobjconstr.nim
  compiler/semstmts.nim
  compiler/sizealignoffsetimpl.nim
  compiler/varpartitions.nim
  compiler/vmgen.nim
  doc/manual_experimental.md
  lib/pure/collections/sequtils.nim
  lib/system.nim
  tests/stdlib/tsequtils.nim
  tests/types/ttopdowninference.nim
Labels: merge_when_passes_CI

#20249 fixes #20219; ignore comment/empty node in stmtListExpr
  compiler/jsgen.nim
Labels: TODO: followup needed, Requires Araq

#20195 move formatfloat out of system
  changelog.md
  compiler/ic/ic.nim
  compiler/lexer.nim
  compiler/renderer.nim
  compiler/rodutils.nim
  compiler/ropes.nim
  compiler/sem.nim
  compiler/semfold.nim
  compiler/types.nim
  compiler/vm.nim
  compiler/vmmarshal.nim
  compiler/vmops.nim
  lib/core/macros.nim
  lib/packages/docutils/rstgen.nim
  lib/pure/json.nim
  lib/std/formatfloat.nim
  lib/std/private/dragonbox.nim
  lib/std/private/schubfach.nim
  lib/std/syncio.nim
  lib/system/chcks.nim
  lib/system/dollars.nim
  lib/system/formatfloat.nim
  lib/system/repr_v2.nim
Labels: v2, Requires Araq

#19441 std/options enables stricteffects
  lib/pure/options.nim
Labels: Nim 2

#19836 fix #19600 No error checking on fclose
  lib/std/syncio.nim
  tests/misc/t19600.nim
Labels: Requires Araq

#20228 [nimsuggest] fix def call on identifier 2 times on the line
  compiler/modulegraphs.nim
  compiler/suggest.nim
  nimsuggest/nimsuggest.nim
  nimsuggest/tests/tv3.nim
  nimsuggest/tests/tv3_definition.nim
Labels: Requires Araq

#20179 Change nim's nimble files to make it installable
  compiler.nimble
  nim.nimble
  nimsuggest/nimsuggest.nimble
Labels: merge_when_passes_CI, Requires Dom96
