Repository nim-lang/Nim, pull requests merged in 2022-10, with the labels that each got.

#20471 new move analyser2
  compiler/aliasanalysis.nim
  compiler/ast.nim
  compiler/ccgcalls.nim
  compiler/dfa.nim
  compiler/injectdestructors.nim
  compiler/int128.nim
  compiler/lambdalifting.nim
  compiler/parampatterns.nim
  compiler/sempass2.nim
  compiler/transf.nim
  lib/pure/collections/sequtils.nim
  tests/arc/tmovebug.nim
  tests/arc/topt_no_cursor.nim
  tests/destructor/t16607.nim
  tests/destructor/tbintree2.nim
  tests/destructor/tmove_objconstr.nim
  tests/destructor/tprevent_assign2.nim
  tests/destructor/tprevent_assign3.nim
  tests/destructor/tuse_ownedref_after_move.nim
Labels: merge_when_passes_CI

#19953 [ARC] fixes #18645; C Compiler error when initializing {.global.} with a block
  compiler/injectdestructors.nim
  tests/arc/t18645.nim
Labels: merge_when_passes_CI

#20496 remove deprecation messages for `unsafeAddr`; add warnings to docs
  lib/system.nim
Labels: merge_when_passes_CI

#20291 fixes #19231; newFinalize doesn't work with ORC
  compiler/semmagic.nim
  tests/arc/t19231.nim
Labels: Requires Araq

#20495 Make output assertion deterministic for test for #7172
  tests/threads/t7172.nim
Labels: merge_when_passes_CI

#20502 follow up #20109; remove `shallow` seqs/strings for ORC
  changelog.md
  doc/nimc.md
  lib/system.nim
  testament/important_packages.nim
  tests/collections/tseq.nim
  tests/converter/t7097.nim
  tests/converter/t7098.nim
  tests/stdlib/tstrutils2.nim
  tests/system/tnilconcats.nim
Labels: Requires Araq To Merge

#20493 Fix/improve handling of forward declarations in nimsuggest
  compiler/modulegraphs.nim
  compiler/options.nim
  compiler/suggest.nim
  nimsuggest/nimsuggest.nim
  nimsuggest/tests/tv3_forward_definition.nim
  nimsuggest/tests/tv3_globalSymbols.nim
Labels: Requires Araq To Merge

#20494 correct grammar (ref #20199) and add check for grammar.txt
  compiler/parser.nim
  doc/grammar.txt
  tests/compiler/tgrammar.nim
Labels: Requires Araq To Merge

#20511 closes #12994; add testcase
  tests/vm/tvmmisc.nim
Labels: merge_when_passes_CI

#17219 FTP client is now able to connect to server over TLS by set `useTls =…
  lib/pure/asyncftpclient.nim
Labels: merge_when_passes_CI

#20523 parseutils: skipWhile: fix parameter name in doc comment
  lib/pure/parseutils.nim
Labels: merge_when_passes_CI

#20472 fix #18886 crash on ambiguous proc cast
  compiler/lookups.nim
  compiler/semexprs.nim
  tests/errmsgs/t18886.nim
Labels: Requires Araq To Merge

#20533 enable nimlsp and ast_pattern_matching
  testament/important_packages.nim
Labels: merge_when_passes_CI

#20522 fix #7446 Generics: type mismatch 'SomeunsignedInt or Natural'
  compiler/sigmatch.nim
  tests/generics/t7446.nim
Labels: Requires Araq To Merge

#20554 fix #18990 Regression in proc symbol resolution; Error: attempting to…
  compiler/semtypes.nim
  tests/constr/a.nim
  tests/constr/b.nim
  tests/constr/t18990.nim
Labels: merge_when_passes_CI

#20555 fix #18136 tests/proc/t17157.nim now gives SIGSEGV instead of error
  compiler/semtypes.nim
  tests/proc/t17157.nim
Labels: Requires Araq To Merge

#20548 fix #8821 JS codegen can produce extreme switch statements with case …
  compiler/jsgen.nim
  tests/js/t8821.nim
Labels: Requires Araq To Merge

#19380 fixes #19162; enable `strictEffects` for v2
  changelog.md
  compiler/nim.cfg
  compiler/options.nim
  compiler/sempass2.nim
  config/config.nims
  doc/manual.md
  lib/pure/pegs.nim
  lib/system.nim
  lib/system/repr_v2.nim
  nimsuggest/sexp.nim
  testament/important_packages.nim
  tests/closure/tnested.nim
  tests/effects/teffects6.nim
  tests/effects/tgcsafe.nim
  tests/effects/tnosideeffect.nim
  tests/stdlib/tpegs.nim
Labels: Showstopper, Requires Araq To Merge

#20577 Fix #12517 Allow single branch when nimvm statements
  compiler/semexprs.nim
  tests/whenstmt/t12517.nim
Labels: Requires Araq To Merge

#20578 [backport] Handle nkOpenSymChoice for nkAccQuoted in considerQuotedIdent
  compiler/lookups.nim
  tests/template/template_various.nim
Labels: merge_when_passes_CI

#20593 [std/os] split and re-export
  compiler/vmops.nim
  lib/pure/os.nim
  lib/std/private/oscommon.nim
  lib/std/private/osdirs.nim
  lib/std/private/osfiles.nim
  lib/std/private/ospaths2.nim
  lib/std/private/ossymlinks.nim
Labels: Showstopper

#20602 change vm imports after bootstrapping
  compiler/vmops.nim
Labels: merge_when_passes_CI

#20586 Implemented `mSlice` on the VM allowing `toOpenArray` to work at compile time.
  compiler/vm.nim
  compiler/vmdef.nim
  compiler/vmgen.nim
  tests/vm/topenarrays.nim
Labels: Requires Araq To Merge

#20550 fix #19426 compile error using when/elif/else and typedesc in template
  compiler/semfold.nim
  tests/whenstmt/t19426.nim
Labels: Requires Araq To Merge

#20551 fix #19349 incompatible type when mixing float32 and cfloat in generics
  compiler/types.nim
  tests/alias/t19349.nim
Labels: Requires Araq To Merge

#20582 add typesafe `std/paths`, `std/files`, `std/dirs`, `std/symlinks`
  lib/std/dirs.nim
  lib/std/files.nim
  lib/std/paths.nim
  lib/std/symlinks.nim
  tests/stdlib/tfilesanddirs.nim
  tests/stdlib/tpaths.nim
Labels: Showstopper

#20615 Unpack mSlice tupleconstr for static openarrays
  compiler/semmacrosanity.nim
  tests/views/tconst_views.nim
  tests/vm/topenarrays.nim
Labels: Requires Araq To Merge

#20620 enable static tests for topenarray
  tests/openarray/topenarray.nim
Labels: merge_when_passes_CI

#20637 Fix tuple size check in `std/jsonutils`
  lib/std/jsonutils.nim
  tests/stdlib/tjsonutils.nim
Labels: merge_when_passes_CI

#20631 fixes #1027; disallow templates to use ambiguous identifiers
  compiler/semtempl.nim
  tests/template/m1027a.nim
  tests/template/m1027b.nim
  tests/template/t1027.nim
Labels: Requires Araq To Merge

#20635 fix #12094 Use of _ (as var placeholder) inside a template causes XDe…
  compiler/semstmts.nim
Labels: Requires Araq To Merge

#20651 clean up `std/os` related modules
  lib/pure/os.nim
  lib/std/dirs.nim
  lib/std/paths.nim
  lib/std/private/oscommon.nim
  lib/std/private/osdirs.nim
  lib/std/private/ospaths2.nim
Labels: merge_when_passes_CI

#20639 fixes #20681; add efSkipFieldVisibilityCheck to skip check
  compiler/semdata.nim
  compiler/semexprs.nim
  compiler/semobjconstr.nim
  compiler/semtypes.nim
  tests/objects/tdefaultfieldscheck.nim
  tests/objects/tdefaultrangetypescheck.nim
  tests/objects/tobject_default_value.nim
Labels: merge_when_passes_CI

#20686 alternate fix + test for #12094, refs #13804
  compiler/semstmts.nim
  compiler/semtempl.nim
  tests/template/tunderscore1.nim
Labels: Requires Araq To Merge

#20713 removes channels_builtin when enabling `nimPreviewSlimSystem`
  changelog.md
  doc/lib.md
  lib/impure/rdstdin.nim
  lib/pure/collections/deques.nim
  lib/pure/concurrency/threadpool.nim
  lib/system.nim
  tools/kochdocs.nim
Labels: merge_when_passes_CI
