Repository nim-lang/Nim, pull requests merged in 2022-11, with the labels that each got.

#20702 fix #20272 range of uint64 shows signed upper bound
  compiler/types.nim
  tests/misc/t6549.nim
Labels: Requires Araq To Merge

#20339 fix semcase on tySequence and tyObject #20283 #19682
  compiler/semcall.nim
  compiler/semdata.nim
  compiler/semstmts.nim
  tests/errmsgs/tcase_stmt.nim
Labels: Requires Araq To Merge

#20722 fixes ssl static link regression
  lib/wrappers/openssl.nim
Labels: merge_when_passes_CI

#20741 fixes #20740; fixes pre-existing field visibility issues and removes `efSkipFieldVisibilityCheck`
  compiler/ast.nim
  compiler/semdata.nim
  compiler/semobjconstr.nim
  compiler/vmgen.nim
  tests/objects/tobject_default_value.nim
Labels: merge_when_passes_CI

#20751 add `effectsOf` to `std/tables`
  lib/pure/collections/tables.nim
Labels: merge_when_passes_CI

#20752 Support doc comments in new-styled concepts
  compiler/concepts.nim
  tests/concepts/t20237.nim
Labels: merge_when_passes_CI

#20760 add effectsOf to map in the std/sets module
  lib/pure/collections/sets.nim
Labels: merge_when_passes_CI

#20764 Revert "fix arc global variable issues"
  .github/workflows/ci_docs.yml
  compiler/injectdestructors.nim
  tests/arc/tarcmisc.nim
Labels: merge_when_passes_CI

#20766 fixes regression #17121; adding doc comment in importc proc makes it silently noop at CT
  compiler/vmgen.nim
  tests/vm/t17121.nim
Labels: merge_when_passes_CI

#20786 fixes nightlies regression; patches for freebsd
  lib/posix/posix_macos_amd64.nim
Labels: merge_when_passes_CI

#20781 implements display based subtype checking (6.4x faster without threads; 2.8x faster with threads)
  compiler/ccgexprs.nim
  compiler/ccgstmts.nim
  compiler/ccgtypes.nim
  lib/system.nim
  lib/system/arc.nim
Labels: merge_when_passes_CI

#20796 add more `{.cursor.}` to vm
  compiler/vm.nim
Labels: merge_when_passes_CI

#20795 reduce openArray-related C undefined behavior
  compiler/ccgcalls.nim
  compiler/ccgexprs.nim
  compiler/cgen.nim
Labels: merge_when_passes_CI

#20804 fixes #13781; fixes #14901; add acyclic pragmas to FlowVar
  lib/pure/concurrency/threadpool.nim
  tests/parallel/tlet_spawn.nim
Labels: merge_when_passes_CI

#20815 switch to official docopt URL
  testament/important_packages.nim
Labels: merge_when_passes_CI

#20816 support `UncheckedArray[T]` in repr_v2.nim
  lib/system/repr_v2.nim
  tests/arc/trepr.nim
Labels: Requires Araq To Merge

#20825 [minor] documentation improvement
  lib/std/decls.nim
Labels: merge_when_passes_CI

#20806 Revert "fixes #20699; generate an empty struct for void type"
  compiler/ccgexprs.nim
  compiler/ccgtypes.nim
  tests/objects/tobject_default_value.nim
Labels: merge_when_passes_CI

#20812 fix #3505 wrong var {.global.} initialization, asign variable to it
  compiler/semstmts.nim
  tests/global/t3505.nim
Labels: merge_when_passes_CI

#20831 fixes flaky CI with channels and ORC
  tests/threads/ttryrecv.nim
Labels: merge_when_passes_CI

#20839 fixes object default fields bugs and add tests
  compiler/sem.nim
  compiler/semmagic.nim
  compiler/semobjconstr.nim
  tests/objects/tobject_default_value.nim
Labels: merge_when_passes_CI

#20824 createDir is now callable at compile time
  compiler/vmops.nim
Labels: Requires Araq To Merge

#20849 fixes a long-standing ARC bug
  compiler/aliasanalysis.nim
  tests/arc/tarcmisc.nim
Labels: Showstopper

#20832 fixes a severe bug of testament
  lib/system/alloc.nim
  testament/testament.nim
  tests/destructor/topttree.nim
  tests/misc/ttlsemulation.nim
  tests/threads/t7172.nim
  tests/threads/t8535.nim
  tests/threads/threadex.nim
  tests/threads/tjsthreads.nim
  tests/threads/tmanyjoin.nim
  tests/threads/tonthreadcreation.nim
  tests/threads/tracy_allocator.nim
  tests/threads/treusetvar.nim
  tests/threads/tthreadvars.nim
Labels: merge_when_passes_CI

#20859 fixes #20856; store defaults directly
  compiler/semobjconstr.nim
  compiler/transf.nim
  tests/objects/tobjects_various.nim
Labels: merge_when_passes_CI

#20867 remove useless defines
  lib/wrappers/postgres.nim
Labels: merge_when_passes_CI

#20888 Fix compiler build with -d:nimDebugReorder
  compiler/reorder.nim
Labels: Requires Araq To Merge

#20896 correct Ptr field name for RTL_CONDITION_VARIABLE?
  lib/std/private/syslocks.nim
Labels: merge_when_passes_CI

#20882 NimMain/NimPreMain calls are now only volatile when it makes sense.
  compiler/cgen.nim
Labels: Requires Araq To Merge

#20876 fix #20866 [ORC] Bad codegen for global pointer to iterator
  compiler/semstmts.nim
  tests/global/t3505.nim
Labels: Requires Araq To Merge

#20864 fixes #20026; marks system procs which can raise defects
  compiler/ast.nim
  compiler/ccgcalls.nim
  compiler/condsyms.nim
  compiler/pragmas.nim
  compiler/wordrecg.nim
  lib/system/indices.nim
  tests/stdlib/tstring.nim
Labels: Requires Araq To Merge

#20862 fix #18964 Small string case with else statement first in AST evaluat…
  compiler/semstmts.nim
  tests/casestmt/t18964.nim
Labels: Requires Araq To Merge

#20871 render post expr blocks better
  compiler/renderer.nim
  tests/stdlib/trepr.nim
Labels: Requires Araq To Merge

#20904 remove enabled defines in config
  tests/config.nims
Labels: merge_when_passes_CI

#20761 fix #13790; ptr char (+friends) should not implicitly convert to cstring
  changelog.md
  compiler/nim.cfg
  compiler/sigmatch.nim
  tests/stdlib/config.nims
  tests/tools/config.nims
Labels: Requires Araq To Merge

#20920 Handle ppc CPU architecture
  tools/niminst/makefile.nimf
Labels: Requires Araq To Merge

#20952 move `asyncftpclient` to nimble packages
  lib/pure/asyncftpclient.nim
  tests/effects/tstrict_funcs_imports.nim
Labels: Requires Araq To Merge

#20931 fix bugs with dot & call operators [backport]
  compiler/semcall.nim
  compiler/semexprs.nim
  nimsuggest/tests/tgeneric_highlight.nim
  tests/concepts/texplain.nim
  tests/specialops/terrmsgs.nim
  tests/specialops/tnewseq.nim
Labels: Requires Araq To Merge

#20935 allow proc expressions in place of statements
  compiler/parser.nim
  tests/parser/tprocexprasstmt.nim
Labels: Requires Araq To Merge

#20947 fixes #13583; enforce void for `nkWhileStmt`
  compiler/semstmts.nim
  tests/discard/tdiscardable.nim
Labels: Requires Araq To Merge

#20960 fixes documentation regression
  doc/nims.md
Labels: merge_when_passes_CI

#20950 Add `--genCDeps` for better integration with CMake
  compiler/commands.nim
  compiler/main.nim
  compiler/options.nim
Labels: Requires Araq To Merge

#20953 move `smtp` to nimble packages
  changelog.md
  doc/lib.md
  koch.nim
  lib/pure/smtp.nim
  tests/effects/tstrict_funcs_imports.nim
  tests/js/tstdlib_imports.nim
Labels: Requires Araq To Merge
