Repository nim-lang/Nim, pull requests merged in 2022-09, with the labels that each got.

#19996 [Testament] Extend and document message testing aids
  doc/testament.md
  testament/specs.nim
  testament/testament.nim
  tests/arc/topt_cursor.nim
  tests/arc/topt_no_cursor.nim
  tests/casestmt/tincompletecaseobject2.nim
  tests/effects/teffects1.nim
  tests/errmsgs/tinteger_literals.nim
  tests/pragmas/tvar_macro.nim
  tests/readme.md
  tests/stdlib/t8925.nim
  tests/strictnotnil/tnilcheck.nim
  tests/testament/tinlinemsg.nim
  tests/testament/tshould_not_work.nim
  tests/views/tdont_mutate.nim
Labels: Requires Araq

#20133 remove the old nimv019 define in the config
  config/nim.cfg
Labels: Requires Araq

#20130 support cstring in `case`
  changelog.md
  compiler/ccgstmts.nim
  compiler/cgen.nim
  compiler/condsyms.nim
  compiler/dfa.nim
  compiler/jsgen.nim
  compiler/optimizer.nim
  compiler/sempass2.nim
  compiler/semstmts.nim
  compiler/semtypes.nim
  doc/manual.md
  lib/system/strmantle.nim
  tests/casestmt/tcstring.nim
Labels: Requires Araq

#19754 Fix #16937; --clib option pass library name to backend C compiler correctly
  compiler/commands.nim
  tests/compiler/samplelib.nim
  tests/compiler/tcmdlineclib.nim
  tests/compiler/tcmdlineclib.nims
Labels: merge_when_passes_CI

#20296 Partially Revert "Change nim's nimble files to make it installable"
  nimsuggest/nimsuggest.nimble
Labels: Ready For Review

#20199 remove deprecated type pragma syntax, fix bugs that required it
  changelog.md
  compiler/parser.nim
  compiler/semstmts.nim
  doc/grammar.txt
  doc/manual.md
  lib/pure/concurrency/atomics.nim
  lib/pure/pegs.nim
  testament/categories.nim
  testament/important_packages.nim
  tests/assign/tassign.nim
  tests/ast_pattern_matching.nim
  tests/bind/told_bind_expr.nim
  tests/ccgbugs/targ_lefttoright.nim
  tests/ccgbugs/tccgen1.nim
  tests/ccgbugs/tmissingbracket.nim
  tests/cpp/tdont_init_instantiation.nim
  tests/cpp/temitlist.nim
  tests/cpp/tvector_iterator.nim
  tests/effects/teffects2.nim
  tests/effects/teffects3.nim
  tests/effects/teffects4.nim
  tests/errmsgs/tinvalidinout.nim
  tests/exception/tcpp_imported_exc.nim
  tests/generics/module_with_generics.nim
  tests/generics/tcan.nim
  tests/generics/tgeneric3.nim
  tests/generics/tinheritable_importcpp.nim
  tests/iter/titer2.nim
  tests/macros/tgettypeinst.nim
  tests/macros/tvtable.nim
  tests/method/tmethod_issues.nim
  tests/method/tmethod_various.nim
  tests/method/tmultim.nim
  tests/misc/tsimplesort.nim
  tests/objects/tobjconstr2.nim
  tests/objects/tobjects_various.nim
  tests/statictypes/tstaticimportcpp.nim
  tests/stdlib/tstrset.nim
  tests/typerel/tcommontype.nim
  tests/types/tfinalobj.nim
  tests/types/tinheritref.nim
  tests/types/told_pragma_syntax1.nim
  tests/types/told_pragma_syntax2.nim
  tools/grammar_nanny.nim
Labels: Requires Araq

#20126 only allow enums to overload enums + extra test
  compiler/semexprs.nim
  tests/enum/toverloadable_enums.nim
Labels: Requires Araq

#20300 Prevent use-after-free bugs in object variants. Fixes bug #20305
  compiler/liftdestructors.nim
Labels: Requires Araq

#20267 Replace `if` by `case` in JS `isSimpleExpr`
  compiler/jsgen.nim
Labels: Requires Araq

#20307 fixes #20303; wasMoved expressions with side effects for ORC
  compiler/injectdestructors.nim
  tests/arc/tarc_orc.nim
Labels: Requires Araq

#20319 Markdown links migration part 1
  doc/backends.md
  doc/contributing.md
  doc/destructors.md
  doc/docgen.md
  doc/manual.md
  doc/manual_experimental.md
  doc/sets_fragment.txt
  doc/tut1.md
  doc/tut2.md
  doc/tut3.md
  lib/packages/docutils/rst.nim
  tests/stdlib/trst.nim
Labels: merge_when_passes_CI

#20315 fix #13515 [backport]
  compiler/semtempl.nim
  tests/template/t13515.nim
Labels: merge_when_passes_CI

#20158 fixes #20155; repr range with distinct types is broken with ORC
  compiler/semmagic.nim
  lib/system/repr_v2.nim
  tests/metatype/tmetatype_various.nim
Labels: Requires Araq

#20323 Add testcase for bug #20305
  tests/arc/tcaseobj.nim
Labels: merge_when_passes_CI

#19528 nimgrep: add `--inContext` and `--notinContext` options
  doc/nimgrep.md
  doc/nimgrep_cmdline.txt
  tests/tools/tnimgrep.nim
  tools/nimgrep.nim
Labels: merge_when_passes_CI

#20352 fixes #19104; peg Incorrect captures [backport:1.6]
  lib/pure/pegs.nim
  tests/stdlib/tpegs.nim
Labels: Requires Araq

#20344 Allow custom pragma on iterators [backport]
  compiler/pragmas.nim
  tests/pragmas/tcustom_pragma.nim
Labels: merge_when_passes_CI

#20327 fixes #19713; Revert "Remove tlsEmulation enabled from Windows + GCC config" (#19119)
  compiler/nim.cfg
  compiler/ropes.nim
  config/nim.cfg
  tests/config.nims
Labels: Requires Araq

#20370 Shorten JS block code
  compiler/jsgen.nim
Labels: Requires Araq

#20388 turn nimIncrSeqV3 into deadcode
  changelog.md
  compiler/condsyms.nim
  lib/system/gc.nim
  lib/system/sysstr.nim
Labels: Requires Araq

#20395 fixes #20391; make of operator work with generics for ORC
  compiler/ccgtypes.nim
  tests/method/tmethod_issues.nim
Labels: Requires Araq

#19771 RFC-460 implemented
  changelog.md
  lib/system/seqs_v2.nim
  lib/system/strs_v2.nim
Labels: Requires Araq

#20338 fixes #20285; prevent oid time overflow at year 2038
  changelog.md
  lib/pure/oids.nim
  tests/stdlib/toids.nim
Labels: merge_when_passes_CI

#20377 Fixes #20348; only respect the recursion limit if the symbol's generic type has been generated by the compiler
  compiler/ast.nim
  compiler/semstmts.nim
  compiler/semtypinst.nim
  tests/generics/tgeneric_recursionlimit.nim
Labels: Requires Araq

#20407 fix #17351; switch to c++17 and remove hacks
  compiler/cgen.nim
  compiler/extccomp.nim
  tests/cpp/torc.nim
Labels: Requires Araq

#20414 close #15955; add a test case
  tests/misc/m15955.nim
  tests/misc/m15955_main.nim
  tests/misc/t15955.nim
Labels: merge_when_passes_CI

#20379 fix #2614 improve error message when array of proc calling convention…
  compiler/types.nim
  tests/effects/teffects1.nim
  tests/errmsgs/t2614.nim
  tests/errmsgs/tproc_mismatch.nim
Labels: Requires Araq

#20411 Represent more types as JS `TypedArray`s
  compiler/jsgen.nim
Labels: Requires Araq

#20270 allow more simple expressions in js
  compiler/jsgen.nim
Labels: Requires Araq

#20295 fixes #19401; fixes #19402; rework Forward declaration and finalizer for ORC
  compiler/semmagic.nim
  tests/arc/t19401.nim
  tests/arc/t19402.nim
Labels: Requires Araq

#20134 fixes #19986; mutable view from immutable location
  compiler/varpartitions.nim
  tests/views/t19986.nim
Labels: Requires Araq

#20115 store full definition AST for consts, fix noRewrite
  changelog.md
  compiler/ast.nim
  compiler/ccgexprs.nim
  compiler/ccgliterals.nim
  compiler/guards.nim
  compiler/injectdestructors.nim
  compiler/jsgen.nim
  compiler/parampatterns.nim
  compiler/patterns.nim
  compiler/pragmas.nim
  compiler/semcall.nim
  compiler/semexprs.nim
  compiler/semfold.nim
  compiler/sempass2.nim
  compiler/semstmts.nim
  compiler/sighashes.nim
  compiler/suggest.nim
  compiler/transf.nim
  compiler/vmgen.nim
  lib/core/macros.nim
  tests/deprecated/tconst.nim
  tests/macros/t19766_20114.nim
  tests/macros/tgetimpl.nim
  tests/pragmas/tcustom_pragma.nim
  tests/trmacros/tnorewrite.nim
  tests/trmacros/trmacros_various.nim
Labels: merge_when_passes_CI

#20355 moderate system cleanup & refactor
  changelog.md
  compiler/lexer.nim
  compiler/renderer.nim
  doc/manual.md
  lib/core/typeinfo.nim
  lib/posix/posix_haiku.nim
  lib/posix/posix_nintendoswitch.nim
  lib/pure/memfiles.nim
  lib/pure/nativesockets.nim
  lib/pure/os.nim
  lib/pure/ssl_certs.nim
  lib/pure/terminal.nim
  lib/std/syncio.nim
  lib/system.nim
  lib/system/ansi_c.nim
  lib/system/arithmetics.nim
  lib/system/basic_types.nim
  lib/system/chcks.nim
  lib/system/comparisons.nim
  lib/system/compilation.nim
  lib/system/ctypes.nim
  lib/system/exceptions.nim
  lib/system/indices.nim
  lib/system/iterators.nim
  lib/system_overview.rst
  lib/windows/winlean.nim
  nimsuggest/tests/tsug_typedecl.nim
  nimsuggest/tests/ttype_decl.nim
  tests/cpp/tretvar.nim
  tests/misc/tradix.nim
  tests/misc/tunsignedconv.nim
  tests/misc/tvarnums.nim
  tests/range/trange.nim
  tests/stdlib/tquit.nim
  tests/stdlib/tstrset.nim
  tests/vm/tzero_extend.nim
  tools/kochdocs.nim
Labels: merge_when_passes_CI

#20444 Unicode Operators are no longer experimental
  changelog.md
  compiler/lexer.nim
  compiler/options.nim
  doc/manual.md
  doc/manual_experimental.md
  tests/lexer/nim.cfg
Labels: merge_when_passes_CI

#20455 fixes postgres with `nimPreviewSlimSystem`
  lib/wrappers/postgres.nim
Labels: merge_when_passes_CI
