Repository nim-lang/Nim, pull requests merged in 2023-04, with the labels that each got.

#21643 terminal size env-vars have precendence in POSIX
  lib/pure/terminal.nim
Labels: merge_when_passes_CI

#21165 fix #20997
  lib/system/sets.nim
Labels: Requires Araq To Merge

#21688 fixes #21540; deref block at transf phase to make injectdestructors function properly
  compiler/ccgexprs.nim
  compiler/transf.nim
  tests/ccgbugs/tderefblock.nim
Labels: merge_when_passes_CI

#21695 Fix json.to for float fields that are not present
  lib/pure/json.nim
Labels: Standard Library

#21699 add test for #13764
  tests/sets/t13764.nim
Labels: merge_when_passes_CI

#21662 Documented path substitution by compiler
  doc/manual.md
  doc/nimc.md
  lib/system/nimscript.nim
Labels: Requires Araq To Merge

#21707 fix iterator equality + add test for proc equality + fix sameType
  compiler/sigmatch.nim
  compiler/types.nim
  lib/system.nim
  lib/system/comparisons.nim
  lib/system/repr_v2.nim
  tests/system/tcomparisons.nim
  tests/typerel/tproctypeclass.nim
Labels: merge_when_passes_CI

#21648 Pragma to force the exportc of a type. #21645
  compiler/ccgtypes.nim
Labels: merge_when_passes_CI
