Repository nim-lang/Nim, pull requests merged in 2023-03, with the labels that each got.

#21455 Fix #21452; enable Norm in important packages.
  testament/important_packages.nim
Labels: merge_when_passes_CI

#21378 suggestion for a simple fix for #21279
  compiler/cgen.nim
Labels: Requires Araq To Merge

#21351 fixes #10938; fixes #13312; fixes #13918; fixes #20985; always initializes global variables with null values in VM
  compiler/vmgen.nim
  tests/vm/tvmmisc.nim
Labels: Requires Araq To Merge

#21444 replaces implicit passes array registed at runtime with explicit function calls; simplify compilation pipeline
  compiler/cgen.nim
  compiler/depends.nim
  compiler/docgen2.nim
  compiler/jsgen.nim
  compiler/main.nim
  compiler/modulegraphs.nim
  compiler/modules.nim
  compiler/nimeval.nim
  compiler/passes.nim
  compiler/pipelines.nim
  compiler/pipelineutils.nim
  compiler/scriptconfig.nim
  compiler/sem.nim
  compiler/suggest.nim
  compiler/vm.nim
  doc/refc.md
  nimsuggest/nimsuggest.nim
Labels: Requires Araq To Merge

#21469 remove nosinks hacks from compiler
  compiler/cgen.nim
  compiler/depends.nim
  compiler/passes.nim
  compiler/sem.nim
  compiler/semcall.nim
  compiler/seminst.nim
  compiler/semstmts.nim
  compiler/sigmatch.nim
  compiler/vm.nim
Labels: merge_when_passes_CI

#21466 Add line directives for C code variables
  compiler/cgen.nim
Labels: merge_when_passes_CI

#21488 a better message if graphviz's dot/nodejs is not found in PATH
  compiler/main.nim
  compiler/nodejs.nim
Labels: TODO: followup needed

#21530 fixes #19857; Exception raised in closure may be "skipped" in ORC
  compiler/ccgcalls.nim
  tests/arc/tarcmisc.nim
Labels: merge_when_passes_CI

#21511 fixes #21505 (overload resolution of explicit constructors for imported C++ types)
  compiler/ccgtypes.nim
  compiler/cgen.nim
  tests/ccgbugs/tbug21505.nim
Labels: merge_when_passes_CI

#21563 tuple unpacking for vars as just sugar, allowing nesting
  changelogs/changelog_2_0_0.md
  compiler/parser.nim
  compiler/pipelines.nim
  compiler/semexprs.nim
  compiler/semstmts.nim
  doc/grammar.txt
  doc/manual.md
  tests/arc/t19364.nim
  tests/macros/tastrepr.nim
  tests/misc/t11634.nim
  tests/parser/ttupleunpack.nim
  tests/tuples/mnimsconstunpack.nim
  tests/tuples/tnimsconstunpack.nim
Labels: merge_when_passes_CI
