Repository nim-lang/Nim, pull requests merged in 2024-05, with the labels that each got.

#23557 fixes #23556; typeinfo.extendSeq generates random values in ORC
  lib/core/typeinfo.nim
  lib/system/seqs_v2.nim
  tests/stdlib/ttypeinfo.nim
Labels: merge_when_passes_CI

#23570 Improve strutils.rsplit doc, proc and iterator have oppose result order.
  lib/pure/strutils.nim
Labels: merge_when_passes_CI

#23590 Add directory input support to nimpretty
  nimpretty/nimpretty.nim
Labels: Nimpretty

#23633 fixes `reifiedOpenArray`; `nkHiddenStdConv` is PathKinds1 not PathKinds0
  compiler/ccgcalls.nim
Labels: merge_when_passes_CI

#23650 Handle arbitrarily long symlink target in `expandSymlinks()`
  lib/std/private/ossymlinks.nim
Labels: merge_when_passes_CI

#23279 fixes #22852; fixes #23435; fixes #23645; SIGSEGV when slicing string or seq[T] with index out of range
  compiler/cgen.nim
  lib/system/indices.nim
Labels: Showstopper, merge_when_passes_CI

#23653 revert #23436; remove workaround
  lib/system/indices.nim
Labels: merge_when_passes_CI

#23651 Treat CJK Ideographs as letters in `isAlpha()`
  lib/pure/includes/unicode_ranges.nim
  tests/stdlib/tunicode.nim
  tools/unicode_parsedata.nim
Labels: merge_when_passes_CI
