Repository nim-lang/Nim, pull requests merged in 2024-04, with the labels that each got.

#23484 fixes #4299 #12492 #10849; lambda lifting for JS backend
  changelog.md
  compiler/jsgen.nim
  compiler/lambdalifting.nim
  compiler/transf.nim
  lib/js/jsffi.nim
  lib/system/jssys.nim
  tests/js/t21439.nim
  tests/js/tjsffi.nim
  tests/js/tjsffi_old.nim
  tests/stdlib/tclosures.nim
Labels: Javascript

#23498 [JS backend] improve `discard` statement; ridding of the awkward special variable `_`
  compiler/jsgen.nim
  tests/js/tjsffi.nim
Labels: Javascript

#23507 fixes #23505; fixes injectdestructors errors on transformed addr (deref) refs
  compiler/injectdestructors.nim
  tests/arc/tarcmisc.nim
Labels: merge_when_passes_CI

#23493 fixes #4695; closure iterators support for JS backend
  compiler/closureiters.nim
  compiler/jsgen.nim
  compiler/lambdalifting.nim
  doc/manual.md
  lib/system/jssys.nim
  tests/js/t7109.nim
Labels: Javascript

#23508 remove `|| []` from jsgen because string cannot be nil anymore
  compiler/jsgen.nim
Labels: Javascript

#23512 Fix duplicated member declarations in structs for C++ backend
  compiler/semstmts.nim
  tests/cpp/tmember_forward_declaration.nim
Labels: C++ Code Generation

#23538 fixes #23522; fixes pre-existing wrong type for iter in `liftIterSym`
  compiler/lambdalifting.nim
  tests/js/t7109.nim
Labels: merge_when_passes_CI
